CHANGELOG.md
Functions/Coverage.ps1

Is now compatible with DSC in PowerShell 5.0; the AST has changed in this version with regard to dynamic keywords, and it broke some of our code.

Updated Coverage code

---

Functions/Describe.ps1

This should stop us from getting "a variable named TestDrive already exists" errors when running tests multiple times in the same PowerShell session, when the tests are aborted instead of letting Pester finish execution.
Fixes #250

Moved TestDrive code into try/catch/finally

---

CHANGELOG.md
Functions/Assertions/Should.ps1
Functions/Describe.ps1
Functions/InModuleScope.ps1
Functions/Mock.ps1
Functions/PesterState.ps1
Functions/SetupTeardown.ps1
Functions/TestDrive.ps1
Pester.psd1
Pester.psm1

I did some profiling of the module today, and identified several hotspots that have been improved in this commit.  The main three are:
ScriptProperties on the PesterState object (FailedCount, etc) have been replaced with normal properties that are incremented in the AddTestResult function.
Parsing performed for the BeforeEach / AfterEach commands is run a lot and was expensive; this code has been moved into some compiled C# for more speed.
Calls to Get-IgnoreErrorPreference were also adding up quite a bit.  These have been replaced with a lookup of a script-scope variable instead.  This results in a tiny bit of duplication in the Mock code, but it's well worth it.
There are a few lesser changes as well.  On my WMF 5.0 system, the time it takes to execute Pester's own test suite has gone …

Performance improvements

---

Functions/Mock.Tests.ps1

Updated Mock alias test to work on PowerShell 2.0 when an executable named dir happens to exist on the system path (which is happening on our CI server, causing the test to fail.)

Tests Update

---

Pester.psm1

When attempting to Import the module when running a script through Powershell ISE, a missing snippets directory will cause the import to fail.

Missing snippets directory causes Import to fail

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Apparently the ResolvedCommand property on an AliasInfo object is sensitive to the scope from which it's queried; when we're crossing script module boundaries, we need to fetch the value of ResolvedCommand in the scope where the alias was found, not in Pester.

Fix for mocking aliases

---

Functions/Assertions/Should.ps1
Functions/It.ps1

My attempt to implement the behavior described in #265

Add one-line snippet from failure to provide a context

---

Functions/Assertions/BeNullOrEmpty.ps1
Functions/It.ps1
Functions/Mock.ps1
Functions/TestResults.Tests.ps1
Functions/TestResults.ps1
Pester.psm1

We received a bug report that Pester was breaking if StrictMode were set for the whole PowerShell session.  (We've been enabling it at the beginning of each test script, but apparently that's not enough to ensure compliance.  We'll need to enable it before calling Invoke-Pester in our build jobs instead.)
All of these errors have been fixed.

Making Pester StrictMode compliant again.

---

CHANGELOG.md
Functions/InModuleScope.ps1

When multiple modules with the same name are loaded.  Fixes #275 .

Improved error message in InModuleScope

---

Pester.nuspec
build.psake.ps1

nuget apparently has a bug when adding files that have no extension, and the recent addition of LICENSE was causing the pack step to fail.  There's a workaround for this to add a * character to the end of the file name, which appears to work.
I've also tweaked the psake build script slightly to make sure the unversion step works regardless of the $currentDir.

Build script update

---

Pester.nuspec
build.psake.ps1

PowerShellGet packages are currently built expecting the module to be in the root of the NuGet package, so this change allows the build script to specify a custom base for the target in the NuSpec so it can build either Chocolatey or PowerShellGet style packages.
I've left the default behavior to match the current folder structure, but a PowerShellGet module can be built using:
`Invoke-PSake .\build.psake.ps1 -properties @{targetBase = "" }`

Allow NuGet package to be build with module in root

---

Functions/Assertions/Should.ps1
Functions/It.Tests.ps1
Functions/It.ps1

Several references to $Exception were being made when the object is actually an ErrorRecord.  I've renamed those bits to improve clarity, and also added type information to a param block for the same reason.
Added new test to make sure that Get-PesterResult isn't monkeying with failure messages, as mentioned in #282 .

New test of functionality in #282 , plus minor code cleanup.

---

CHANGELOG.md
Functions/BreakAndContinue.Tests.ps1
Functions/Context.ps1
Functions/Describe.ps1
Functions/InModuleScope.ps1
Functions/It.ps1
Pester.Tests.ps1
Pester.psd1
Pester.psm1

This way if the test code (or code under test) has a misplaced break or continue statement, it won't cause the whole Pester run to abort.  (Break / continue statements with labels will still cause this to happen, unfortunately; not sure if there's anything we can do about that.)
Fixes #289

Added do {} until ($true) loops around test script block calls.

---

CHANGELOG.md
Functions/Mock.ps1

Weird ActiveDirectory module is weird.
Fixes #294.  There are no automated tests to verify this yet; we either need to run the test on a 2008 R2 system with the RSAT feature installed, or write some C# code to reproduce the behavior of the AD module.  (The latter would be preferable, but will take some more time.)

Workaround for GetDynamicParameters() bug

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Function and Module names are now injected into the script blocks created based on MockPrototype as plain strings, instead of being read dynamically from the $MyInvocation / $ExecutionContext automatic variables at execution time.  This way, it'll still work even if some goofy code declares parameters with those names.

Fixes #303

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

When mocking a function, if it doesn't contain anything in its dynamicparam block, Pester won't bother injecting the boilerplate code to fetch dynamic parameters when the mock is called.  This avoids potential errors if the function has multiple parameter sets that can't be resolved yet (when pipeline binding is involved.)

Fix for issue #305

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Tweaked the code to remove another instance of relying on $ExecutionContext in the caller's scope at the time a mock is invoked.

Further fixes related to #303

---

Functions/It.ps1
Functions/SetupTeardown.Tests.ps1
Functions/SetupTeardown.ps1
Functions/TestsRunningInCleanRunspace.Tests.ps1

The BeforeEach will fail the test if it throws any error. The After each
is guaranteed to run even if test fails and will also fail the test if
it throws any errors.

Make errors in BeforeEach and AfterEach fail the test

---

Functions/Assertions/Be.ps1
Functions/SetupTeardown.Tests.ps1
Functions/SetupTeardown.ps1

Fixes for #329 and #319 included for v3+.  Also fixes a bug with Should Be / Should BeExactly where they would blow up if empty strings were piped in.

BeforeEach / etc enhancements, and Should Be bug fix

---

Functions/It.ps1
Pester.psm1

Potential fix for #321 
I added a few blank lines to the console output at the beginning of `Invoke-Pester`, to make room for the Progress display.  Tests that finish quickly may not wind up displaying any progress output at all, but long-running tests will provide the user with some feedback about what's happening.

Adding some Write-Progress output to It

---

Functions/GlobalMock-A.Tests.ps1
Functions/GlobalMock-B.Tests.ps1
Functions/Mock.ps1

This works, but there might be some weirdness that can still happen if you mock a global function in conjunction with -ModuleName or InModuleScope.  (The global function gets renamed for the duration of the mock, but the mock is only available from that single module.  You can't mock the same global function from two different modules at once.)
Not sure if it's worth worrying about that edge case, since this "mocking global functions" scenario  is already pretty rare to begin with.
Creating the PR to start discussion on this fix.

Initial fix for #286

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

The new parameter for Assert-MockCalled is called `-NotOtherwise` for now, but I think we may want to come up with a better name.  Either way, the functionality is implemented now.
Assert-MockCalled now throws the same type of ErrorRecord objects as the Should command, which gets us better output as noted in #269.

Fixes for #315 and #269

---

chocolateyInstall.ps1

Adds \bin folder to PATH for easier install and calling Pester.

Add bin folder to PATH

---

Functions/Coverage.Tests.ps1
Functions/Coverage.ps1

Add hit commands property to CodeCoverage object, by exposing the data pester already has.
I believe this helps address #212 by allowing the creation of adapter/translators that can create code coverage reports rather than making pester proper responsible for it.
This would not prevent pester for generating reports itself in the future, but different users may have different needs and I cannot find a clear solution to which report is best. This method would allow for easier experimentation.

Add hit commands property to CodeCoverage object

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1
Functions/SetupTeardown.ps1

This is to fix #345 .
I've added a bunch of new tests related to types of code that might be encountered in a dynamicparam block in a function that we want to mock successfully, and an extremely ugly new hack to fix the problem with ambiguous parameter sets at the time the dynamicparam block is evaluated (but without also breaking the dynamicparam code's ability to use $PSCmdlet.ParameterSetName in its logic.)
Seems to work so far, but if anyone can think of other types of code / scenarios for dynamicparam logic that we should test, now's a good time.

Dynamic param fix

---

Functions/Coverage.ps1
Functions/In.ps1
Functions/New-Fixture.ps1
en-US/about_BeforeEach_AfterEach.help.txt
en-US/about_Mocking.help.txt
en-US/about_Pester.help.txt
en-US/about_TestDrive.help.txt
en-US/about_should.help.txt

Noticed some typos and the like in the help files.

Corrected spelling and capitalization in help and comments.

---

Functions/Assertions/Exist.Tests.ps1
Functions/Assertions/Exist.ps1

Fixing bug which caused that paths that contain [ ] wildcard were not
handled correctly by the Should Exist assertion.
It's morning am not 100 % sure that this won't break anything. But my reasoning is that any path that is provided is expanded by PowerShell (like path with environment variables) so no special handling is needed there. Same goes for PS(Provider)Paths... nothing else comes to mind. 
Review please. :)
Fixes #343

Fix Should Exist assertion to handle paths with [ ]

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Fixes #353 .  $ArgumentList variable in the MockPrototype code has been renamed to ${a r g s}, to avoid naming / validation conflicts.

Fix for mocking cmdlets with an -ArgumentList parameter

---

Functions/It.Tests.ps1
Functions/It.ps1
Functions/TestResults.Tests.ps1
Functions/TestResults.ps1

This pull request addresses Issue #363. I've left the "skip" syntax in place, but have added the alias "ignore" for those who are more familiar with nunit.
I've also modified the nunit reports being generated to not only change from skipped to ignored, but also to fix the run count, removing the number of skipped/ignored count from the number of total tests run.
Please see the screenshot to compare my libraries master branch with that of my pester-tests branch. As you can see, the total number of tests represented is still the same, but it now reports the number of skipped/ignored tests as well.
Also, [here is a discussion](https://groups.google.com/forum/#!topic/nunit-discuss/GH5Zp_WWOdw) on the topic of ignore vs skip.

Feature/issue 363 - Fixes nunit reports generating the incorrect data and also enables an -ignore flag.

---

Functions/Assertions/Contain.Tests.ps1
Functions/Assertions/Contain.ps1
Functions/Assertions/ContainExactly.Tests.ps1
Functions/Assertions/ContainExactly.ps1

fix #377
These are the only places where `Get-Content` is used in assertions.

Fix Unicode issue in `Contain` and `ContainExactly`.

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Dynamic parameter code had an unqualified call to New-Object, which would cause an infinite recursion / stack overflow error if the tests mocked New-Object.

Fixed mocking of New-Object

---

Functions/Mock.ps1

After updating to the most recent windows 10 insider build 10565, some mocks have started to raise errors during testing. An example is when mocking `Test-Path`. This results in:
```
[-] Error occurred in Context block 638ms
A parameter with the name 'OlderThan' was defined multiple times for the command.
```
In previous windows builds, the `Parameters` of a `CommandMetadata` instance will not return dynamic parameters. The dynamic parameters are later added to the mocked command in `Get-DynamicParamBlock`. In build 10565, dynamic parameters are included in the metadata parameters dictionary. So when the dynamic parameters are added later, the mock ends up with duplicate parameters causing the error seen above.
`Test-Path` for instance includes 2 dynamic parameters so mocking it will …

fix dynamic parameter mocks post build 10565

---

Functions/TestResults.ps1

Create and pass an `IO.FileStream` to `XmlWriter.Create()`, since on .NET Core, it does not have an overload for a file path in a string.

Fix XML reporting on .NET Core

---

README.md

The link to the "What's New in Pester 3.0?" wiki article was broken, as it mistakenly included the question mark in the URL (encoded as %3F).

Fix link to "what's new" wiki page

---

Functions/New-Fixture.ps1

Generate case insensitive replacement of 'Test' when converting from
test file name to SUT file name
Fixes  #428

Case insensitive replacement of Test

---

CHANGELOG.md
Functions/Context.ps1
Functions/Describe.ps1
Functions/It.Tests.ps1
Functions/It.ps1
Functions/PesterState.Tests.ps1
Functions/PesterState.ps1
Pester.psm1

*Note: This is my first PR.  While I'm fairly confident about PowerShell and Pester, I'm a git/github novice.*
------
This pull request improves the stack traces and exceptions that Pester outputs to the console.  This is similar to PR #228 except that it (hopefully) addresses the concerns with that PR.
Stack trace outputs are complicated by the fact that `ErrorRecord.ScriptStackTrace` is not available in PowerShell 2.  I did not find a good substitute for `.ScriptStackTrace` under PowerShell 2.  Rather, I opted to use `ErrorRecord.InvocationInfo` to produce a single-line "stack trace" for PowerShell 2.  This is the same technique as is already used in `Get-PesterResult` to produce `TestResult.stackTrace`.
The improvements of this PR over master and #228 are as follows:
* Console Output: …

Improve stack trace and exception console output

---

Functions/Assertions/Set-TestInconclusive.ps1
Functions/It.ps1
Functions/PesterState.ps1
Functions/TestResults.ps1
Pester.psd1
Pester.psm1

Implements #395 .  New Set-TestInconclusive command has an optional -Message parameter, which will be output to the console and in the NUnit XML output.

Adding Set-TestInconclusive

---

Functions/Assertions/Be.ps1
Functions/Assertions/Contain.ps1
Functions/Assertions/ContainExactly.ps1
Functions/Assertions/Exist.ps1
Functions/Assertions/Should.ps1
Functions/Context.ps1
Functions/Coverage.ps1
Functions/Describe.ps1
Functions/In.ps1
Functions/InModuleScope.ps1
Functions/It.ps1
Functions/Mock.Tests.ps1
Functions/Mock.ps1
Functions/New-Fixture.ps1
Functions/PesterState.ps1
Functions/SetupTeardown.ps1
Functions/TestDrive.ps1
Functions/TestResults.ps1
Pester.psm1

Proposed fix for #431 .
Wound up having to change a lot more code than I expected, because we were using module-qualified calls inside of Pester specifically to avoid triggering a user's mock.  For the most part (where scopes don't interfere), this is now addressed by invoking CmdletInfo objects stored in the $script:SafeCommands hashtable, with the call operator `&` instead.
When dot-sourcing test files (such as by pressing F5 in the ISE), lots of things started blowing up, so I went through the module and made sure that almost all of the calls to built-in cmdlets are made safe using the new SafeCommands table.  All seems to be working fine now on PowerShell v2 and v5 on my system (both through Invoke-Pester and with dot-sourcing test scripts), so we should be all set, assuming v3 and v4 …

Mock module qualified calls

---

Functions/Assertions/Should.ps1
Functions/It.ps1
Functions/Mock.Tests.ps1
Functions/Mock.ps1
Functions/PesterState.ps1
Pester.psd1
Pester.psm1

I didn't like exporting another "ignore this" command from Pester, but it's the only way I could think of to solve #436 while not also introducing a regression of #303 .  This way, the only way someone should be able to break things is by mocking Pester's SafeGetCommand function, and I'm comfortable with just saying "don't do that" more than I would be for telling people not to mock Get-Command or not to name a parameter $ExecutionContext (though the latter is pretty iffy; people should really be careful not to overwrite automatic variables.)

Fix for #436

---

Pester.Tests.ps1
Pester.psm1

Fixes #438 .  Added test to make sure that any calls to the SafeCommands table have indexes that actually exist, so we don't forget this sort of thing in the future.

Missing safe command

---

Pester.psm1

Noticed that Invoke-Pester was throwing an exception if no Tests.ps1 files are found, but only in PowerShell v2.  It's due to the behavior of the foreach loop when it enumerates over `$null`, which is a common v2 gotcha.

Small fix for PowerShell v2

---

Functions/TestsRunningInCleanRunspace.Tests.ps1
Pester.psm1

Generate valid NUnit XML for script syntax errors

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

`$args` automatic variable is not used by advanced functions, so it is valid to use `$args` as normal parameter for advanced function. Pester should allow to mock advanced function with such parameter. Same applies to cmdlets with `Args` parameter. Also there is an error when mock for advanced function called with dot operator.

Fix of $args handling

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Single quote does not properly escaped, when command name and module name values got embedded into `MockPrototype`.

Allow mocking commands with single quote in name or module name

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

If advanced function does not specify any positional parameters, then PowerShell make all function parameters to be positional implicitly. This is not true for cmdlets. So that, mock of cmdlet can have different parameter binding behavior compared to original cmdlet. In v3+ you can disable implicit positional parameter binding behavior by specifying `PositionalBinding=$false` in `CmdletBinding` attribute.

Mocking cmdlet without positional parameters

---

Functions/Assertions/PesterThrow.Tests.ps1
Functions/Assertions/PesterThrow.ps1

Speculative support for ErrorId handling in PesterThrow.
Significant increase in complexity of generated messages from PesterThrow, switched to StringBuilder for greater control.
Extended tests to verify backward compatibility and added features.

Added support for ErrorId to PesterThrow

---

Functions/PesterState.ps1
Pester.psd1
Pester.psm1

@rkeithhill , start with this and let me know what you think.  This was just about the quickest and laziest way I could implement this, just to get the ball rolling.  If the new option is specified, the first line of the stack trace gets output in between the failed test header line and the error message.  We can tweak this as needed.  Here's how the usage works (same as you'd expect with New-PSSessionOption / etc):
```posh
$option = New-PesterOption -IncludeVSCodeMarker
Invoke-Pester -PesterOption $option
```

Initial fix for #470

---

README.md

I tried the sample in [README](https://github.com/pester/Pester/blob/2da66db16123f45c97193f775afbde0e3ce5874d/README.md), but it always failed: 
I investigated that, and I found that `Get-Version` and `Get-NextVersion` have to define at somewhere. I recommend that they are also in README with mocking reason.

Fix test failed sample

---

Functions/Assertions/BeLikeExactly.ps1
Functions/Assertions/Should.Tests.ps1

Function names were wrong for the failure messages on Should BeLikeExactly.  This was causing incorrect output for BeLike, and a CommandNotFound error if a BeLikeExactly assertion failed.

Should BeLikeExactly fix

---

en-US/about_BeforeEach_AfterEach.help.txt
en-US/about_Mocking.help.txt
en-US/about_Pester.help.txt
en-US/about_TestDrive.help.txt
en-US/about_should.help.txt

Applied standard formatting rules to Pester About topics. Among other things, this allows the About topics to be included in post-processing tools that look for standard elements in these otherwise unstructured text files.
I also corrected just a few grammatical errors. Really, just a few.

Formatted About topics

---

Pester.Tests.ps1

The assumption is that if you find git.exe on your system, you must be in the Pester repo so you can look for version information. If you've got a release, that's probably not true, even if you have git

Be sure we're in a Pester repo before doing a version check against the repo

---

Functions/PesterState.ps1

$count was $null forcing -First on line 415 to error with a $null param arg. I'm creating the $count variable to ensure $count is always 1.

$count was null

---

en-US/about_Mocking.help.txt

Adds additional links to the See Also section of the help document, highlighting both useful blog posts for getting started with mocking as well as more in depth articles addressing the concept of mocking itself.
Mocks are one of the more complicated requirements of writing good unit tests; the faster we can get users and developers to understand the concept, the better.

Add additional resource links to about_Mocking

---

Pester.psm1

Making sure Parameters key is not null in ResolveTestScripts

---

Pester.psm1

Assertion name and alias checking does two non complementary checks that allow aliases such as `E Q`. 
```powershell
$string = "A A B"
if ( $string -notmatch '\S')  { "invalid" }
if ( $string -match '\S' )    { "valid" }
#outputs: "valid" becuase string contains at least one non-whitespace character
```
So I changed the name checking to skip empty settings and throw on invalid names to notify us about incorrect configuration.
(btw there is one more check `$unresolvedPath -notmatch '\S'` that also does not seem to be doing what it's error message says)

Fix assertion naming constraints to accept single word

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Bug fix in ExecuteBlock

---

Pester.psm1

The pester module will fail to load when someone has a module already loaded that defines a cmdlet with the same name as one of the safe commands. An example of this is FormatPx, which defines Format-Table and Out-String proxy cmdlets (not functions, cmdlets). I have FormatPx loaded in my profile, and when I try to load Pester or invoke a Pester command using 5.1.14393, it fails. This change fixes the problem by adding the -All parameter to all Get-Command calls used to build up the list of safe cmdlets.

Proxy cmdlet support for safe cmdlet lookup

---

Functions/Coverage.Tests.ps1
Functions/Coverage.ps1

PowerShell allows for paths to be written `like\this` or `like/this`, regardless of what the underlying file system wants.  Some of our code was a bit fragile if forward slashes were used; added some normalization code.

Adding support for both forward and back slashes in some paths

---

Functions/Gherkin.Tests.ps1

Gherkin tests run in a job, and they fail when V4 Pester can't be found
in the module path. Tests should be using the Pester version under test,
not globally installed version. So I am importing  the correct module
inside of the job.

Import local Pester version to Gherkin tests

---

Functions/Assertions/PesterThrow.Tests.ps1
Functions/Assertions/PesterThrow.ps1

I replaced the original Contains with IndexOf and a $null check, becuase
Contains returns $True for $null input. The $null in this context means
that users did not specify any expected message and hence all messages
should pass the Get-DoMessagesMatch filter.
There was also a test case which made sure that empty string expectation
returns $False. I removed that case, because it complicates the
contract, and no one is likely using it as it would always fail the
assertion. Instead replaced it with cases that ensure that empty-string
error message will match empty-string expectation.
I also removed the $ExpectedErrorId parameter from Get-DoMessagesMatch,
because it was not used. I guess the idea was to implement the logic of
"id and message must both match" inside of the Get-DoMessageMatch …

Make Should Throw case insensitive

---

Functions/Output.Tests.ps1
Functions/PesterState.ps1
Pester.psm1

Adds Show parameter to Invoke-Pester that filters the output of Pester.
The parameter takes flags of a new type [Pester.OutputTypes]
with the following options: Default, Passed, Failed, Pending,
Skipped, Inconclusive, Describe, Context, Summary.
And three special options: None, All and Fails. The All option is
the default and prints all the output. The None option is replacement
for the -Quiet parameter (still present and not deprecated).
The Fails option shows everything except Passed.
The options can be arbitrarily mixed, for example to provide a very
verbose ouptut that includes only failed tests and summary use:
Invoke-Pester -Show Summary, Failed
The Summary, Failed option is deliberaterly not chosen as the Fails
option because I assume that the Describe and Context information
are …

Add option to Invoke-Pester to filter output

---

Pester.psm1

On Powershell v4 and older the Has-Flag does not cast to the Pester.OutputTypes flagged enum automatically as it does on Powershell v5 which prevents Invoke-Pester from running.

Fix Has-Flag on Powershell v4 and older

---

Functions/PesterState.ps1

Add commas to test run summary as requested on Twitter. 
Is this a breaking change? Is anyone using this to do integrations? I hope not, but in case you do, use the `-PassThru` switch of `Invoke-Pester` to get all the information as PSObjects.

Add commas to summary

---

Functions/TestDrive.ps1

Deprecate Get-TestDriveItem in Pester v. 4.0, update help

---

Functions/Assertions/Be.Tests.ps1
Functions/Assertions/Be.ps1

Fix Should be to behave the same way as in 3.4.6 where the expected side determines the type to be used for comparison. 
Fix #703

Fix Should Be 

---

Examples/Gherkin/Gherkin-Scope.feature
Examples/Gherkin/VariableScope.Steps.ps1
Examples/Validator/Validator.Steps.ps1
Functions/Gherkin.Tests.ps1
Functions/Gherkin.ps1
Functions/GherkinHook.Tests.ps1
Functions/GherkinHook.ps1
Functions/GherkinStep.Tests.ps1
Functions/GherkinStep.ps1
Pester.psd1
Pester.psm1

This should fail -- right now. 
Once it's fixed, it will fix #714 and then you can merge it.

Update Gherkin for Pester 4 Changes

---

Functions/TestResults.Tests.ps1

Used path of powershell instead of hardcoded path to notepad.exe to make it compatible with Linux.

Use OS independent path for resolve test

---

Functions/Environment.Tests.ps1
Functions/Environment.ps1
Pester.Tests.ps1
Pester.psm1

I am trying to make Pester work on Linux (namely the microsoft/powershell docker container), so I am taking it from the most obvious failing tests like the one that checked that Get-OS returns Windows. I added tests in a way that is able to run on any operating system, I am probably doing too much work there, but I wanted to think about different approaches. 
One thing I am not sure about is how would I test with functions that are in the safe command table? I can't mock those.

Add better tests for OS and temp

---

Pester.Tests.ps1

Use `Join-Path` instead of string concatenation with backslash to make the code more compatible with Linux.

Fix paths in Pester.Tests.ps1

---

Functions/PesterState.ps1

Fixed the placement, changed the separator to be `\` which seemed more natural. 
```powershell
'Describe "top" { describe "middle" { context "bottom" { it "whatever" { $true | Should Be $true } } } }' | Out-File -FilePath .\test.ps1
$result = Invoke-Pester -Script .\test.ps1 -PassThru
$result.TestResult
```
```
ErrorRecord            : 
ParameterizedSuiteName : 
Describe               : top
Parameters             : {}
Passed                 : True
Show                   : All
FailureMessage         : 
Time                   : 00:00:00.0974222
Name                   : whatever
Result                 : Passed
Context                : middle\bottom
StackTrace             : 
```
Fixes #751

Swap Describe and Context and order correctly with \ as a separator

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

In the past we've been renaming functions back and forth when mocking an existing function. Apparently we've been lucky that this worked at all, because when we rename the function back, we can wind up modifying its scope.
This PR changes the approach: we never modify the original command, even if it's a function. Instead, we create an alias with the same name (which takes precedence anyway), and point that alias to our mock's bootstrap function that can exist under any name. (Using GUIDs to ensure uniqueness.) When we delete the alias, the original unmocked version of the command goes back to being in effect without any tampering on Pester's part.
Fixes #697

Fixes #697 - Mocking a Dummy Function with a Pipeline in two consequitive Context

---

Functions/Describe.Tests.ps1
Functions/It.ps1
Functions/Mock.Tests.ps1
Functions/Mock.ps1
Functions/PesterState.ps1

Pester internals now track when they are inside an It block, and correctly assign test group scopes to mock calls when this is not the case.
Fixes #746

Fixes #746 - Incorrect Mock call history scopes

---

Functions/Gherkin.ps1
Functions/Output.ps1
Pester.Tests.ps1
Pester.psm1
chocolateyInstall.ps1

- after correction ps1, psm1 files in the root Pester directory are checked by 'Style rules' too
- trailing spaces removed, 
- tabs replace with 4 spaces
The related issue #689

The test Style rules corrected - branch DevelopmentV4

---

Functions/Coverage.Tests.ps1
Functions/Coverage.ps1
Pester.psm1
report.dtd

I have added a parameter called CodeCoverageOutputFile, which will make Pester write the summarised code coverage results in a JaCoCo formatted XML file to the path specified. This XML file is compatible with the VSTS/TFS Code Coverage overview:

Add support for JaCoCo XML code coverage reports.

---

Pester.psd1
Pester.psm1

Allow other modules to extend Pester by making `Add-AssertionOperator` public.

Make Add-AssertionOperator a public function

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

add test 'Works with command with parameter named Keys' to 'Naming conflicts in mocked functions'
use $BoundParameters.get_Keys() instead of $BoundParameters.Keys in Get-ParamBlockFromBoundParameters
fix #776

add tests and use .get_Keys() instead of .Keys [V3Maintenance]

---

Functions/Assertions/Set-TestInconclusive.ps1
Functions/In.ps1
Functions/Mock.ps1
Functions/SetupTeardown.ps1
Functions/TestDrive.ps1
Pester.Tests.ps1

This PR resolves #781 by doing the following:
* add tests that assert that all non-deprecated, non-internal, public Pester commands use CmdletBinding
* add `[CmdletBinding()]` to the signature of those commands that were missing it
* fix the comment-based help synopsis for `Setup` to make identifying public vs. Pester-internal more consistent

Fix Assert-VerifiableMocks silently does not report anything if 'Verifiable' is spelled wrong on one mock

---

Functions/Assertions/Be.Tests.ps1
Functions/Assertions/Be.ps1

self-limit recursion depth to cause fast(er) failure in case cyclic object graphs are encountered
rename IsCollection to IsArray

make ArraysAreEqual safer

---

Functions/Describe.ps1
Functions/TestsRunningInCleanRunspace.Tests.ps1

Fix exception propagating outside of describe when AfterAll throws

---

Functions/Context.ps1
Functions/New-MockObject.ps1

Help of New-MockObject and Context updated

---

Pester.psm1

Should we add additional parameter set for a code coverage related parameters too?

The parameter CodeCoverageOutputFileFormat added - fix #848

---

Pester.Tests.ps1
Pester.psm1

Fixes #891.
I feel it's a bit redundant to have both `Test-AssertionOperatorIsDuplicate` *and* `Assert-AssertionOperatorNameIsUnique` but I didn't want to tear up and refactor _too_ much. Let me know what you think.

Allow assertion operators to be re-registered if they are identical

---

Functions/It.ps1

workaround for #846 
As requested by #321 we added progress reporting, but it adds a lot of overhead and breaks the output on Linux. I am removing it for now, so we can come up with a better solution that would also work for build servers.

Remove progress to make execution faster and fix linux formatting errors

---

Functions/New-Fixture.Tests.ps1
Functions/New-Fixture.ps1

Fix #369 
Additionally, the extension 'ps1' will be stripped from a provided name to don't duplicate it

Update New-Fixture help and add stripping .ps1 from the Name parameter

---

Pester.psm1

Based on the @Jaykul [comment](https://github.com/pester/Pester/issues/808#issuecomment-338449227) the function Invoke-GherkinStep don't need to be exported from Pester.
Update
In the initial version, I proposed to don't export the function Find-GherkinStep what was my mistake

Don't export the function Invoke-GherkinStep

---

README.md

due that Pester is not bundled since 6.0.0-rc2

Remove information about update on PSCore 6.0.x

---

Functions/SetupTeardown.ps1

Current AfterAll synopsis
```
Defines a series of steps to perform at the end of every It block within
the current Context or Describe block.
```
Should be
```
Defines a series of steps to perform at the end of the current Context
or Describe block.
```

Fix AfterAll synopsis for issue #974

---

Functions/Output.Tests.ps1
Functions/Output.ps1

Updated tests to pass with the changes. This is because the previous tests were checking for Pester-internal exception line information which should never have been there, which is the bug :-)

Fix #991 stack trace and Gherkin output from Pester 4 to match Pester 3

---

en-US/about_Should.help.txt

Fix -FileContentMatch example in about_Should.help.txt file.

Fix -FileContentMatch example.

---

.github/ISSUE_TEMPLATE.md

PowerShell does lazy loading, i.e. if `Invoke-Pester` has not been executed yet, then `Get-Module Pester` does not return anything. Therefore the `-ListAvailable` option has to be used when executing the command in a new shell.

Fix GitHub issue template by using the -ListAvailable option on Get-Module when Pester is not already loaded

---

Functions/Coverage.Tests.ps1
Functions/Coverage.ps1

When generating a JaCoCo report along with code coverage, I noticed that the CLASS counter was not correct: if more than 1 file is actually covered, it always show `1`. The only exception is when there are no covered files, then it properly shows 0.
The issue comes from the way `$hitFiles` is determined using `Measure-Object`. Instead, I suggest a slightly different way similar to how other counter are computed. I adapted an existing test to highlight this issue.

JaCoCo report always mentions only 1 file covered instead of the actual number

---

Dependencies/TypeClass/TypeClass.Tests.ps1

Fix #1030
The test was using `ps` alias which I assume does not exist on Linux to avoid yet another `curl` fiasco. The test did not fail because the result was `$null` which is not a collection, which is what we expected.

use full command name instead of alias

---

Dependencies/Format/Format.Tests.ps1
Dependencies/TypeClass/TypeClass.Tests.ps1
Pester.Tests.ps1

Tests for Pester itself are run under CI with the Set-StrictMode set to Latest.
Lack of this declaration for tests in the Dependencies folder causes that some tests fail only under CI not when they are run locally.
The related  [issue](https://github.com/pester/Pester/pull/972#issuecomment-387561125).

Run all tests under Set-StrictMode set to Latest

---

Functions/TestDrive.ps1

Was debugging an issue where if the temp folder backing TestDrive: gets deleted mid-test-run (some bad DSC temp folder cleanup on our end) where
``` powershell
& $SafeCommands['New-PSDrive'] -Name $DriveName -PSProvider FileSystem -Root $directory -Scope Global -Description "Pester test drive"
```
still gets reached because Test-Path TestDrive:\ returns false, and throws because the TestDrive psdrive still being registered. 
During debugging I found the erroraction ignore on Remove-PSDrive and thought that might be swallowing the error leaving testdrive behind. Turned out not to be the case, but is still a bug regardless in my opinion, unless there was some explicit reasoning for ignoring errors. 
Also removed unnecessary hashtable calls for 'out-null' when $null = is more performant and …

improvements in TestDrive.ps1

---

Pester.Tests.ps1
Pester.psm1

Swallow objects that are written to the output pipeline inside test scripts so that they don't get returned by Invoke-Pester when the -PassThru switch is specified.
Also added some tests to validate the new behaviour.

Fix for #1060 - Invoke-Pester -PassThru returns pipeline output from test scripts

---

Functions/Describe.Tests.ps1
Functions/Describe.ps1
Functions/PesterState.ps1
Pester.psm1

Fixes tag warning that appears when we run directly from an editor because the test stack in that case is smaller than 2 and we were only looking at the stack size to determine how deep we are in the structure. This fix adds a flag to the Pester state that determines if we are running directly or via Invoke-Pester by using a switch when we instantiate state directly in Invoke-Pester and no switch when we instantiate in Describe.
Fix #1066

Fix tags filter warning

---

Functions/It.ps1

The "Name" and "Test" parameters were not capitalised correctly.

Capitalise 'Name' and 'Test' parameters

---

Functions/TestResults.ps1
Pester.Tests.ps1
Pester.psm1

I'm definitely missing environment information when running Pester in our CI on Non-Windows platforms. I would love if the logs had that information. This is an attempt at providing that information with tools that will probably be there. I'm using `uname` and `id` to provide that info. If those tools aren't there, we won't be any worse off, but if they are there, then we can provide the test environment pretty well.

Make an attempt to get environment information for non-Windows platforms

---

Functions/It.ps1

Remove quotes when expanding strings in test name

---

Pester.Tests.ps1
Pester.psm1

`Add-AssertionOperator` intends to allow multiple aliases [[see here](https://github.com/pester/Pester/blob/517f40c90f013e3d042d8845c68444c4c8728eb2/Pester.psm1#L212)], but a bug with a private validation function prevents that behavior.
This PR is a bugfix for `Assert-ValidAssertionAlias`, and adds one test to ensure future adherence.

Allow assertions with multiple aliases

---

Pester.psm1

Some *nix's have symbolic links such as /bin -> /usr/bin which cause Get-Command to retrieve multiple instances. This causes the module to not load on those systems.
The ubuntu* releases don't seem to do this, but CentOS, for example, has `/bin` as a symlink to `/usr/bin` which causes the problem.

Take only the first instance of the id and uname utilities.

---

Pester.Tests.ps1

I had a PR build fail due to an unrelated unit test failing. But, just
to be sure, I checked out my branch locally and ran the entire test
suite starting at the root.
Lo and behold, I had some failing tests--but all due to ensuring that
the correct module manifest version is being found. I also found that at
least one test was skipped if the git remote did not contain 'github.com/Pester/'.
It seems to me that the other tests in the same area of the suite which
also check module versioning information should also not run if the
current git repository is a fork.
This commit moves those tests inside the `if` statement which checks
whether or not the current git repository is the official Pester
repository, or whether or not it's a fork.
After this change, the test suite ran to completion …

Don't run Pester version tests on forks

---

Functions/InModuleScope.Tests.ps1
Pester.psm1

We use **ScriptBlock** with **InModuleScope**.
Now we can use it like this:
```powershell
Describe "{}" {
$ScriptBlock = {Write-Output -InputObject 'This is a ScriptBlock'}
Import-Module -Name PowerShellGet
InModuleScope -ModuleName PowerShellGet -ScriptBlock $ScriptBlock
}
```
the result is:
```powershell
Describing {}
```
But if we need to construct ScriptBlock dynamicly by using **[ScriptBlock]::Create** method
```powershell
Describe "[ScriptBlock]::Create" {
$ScriptBlockText = "Write-Output -InputObject 'This is a ScriptBlock'"
$ScriptBlock = [ScriptBlock]::Create($ScriptBlockText)
Import-Module -Name PowerShellGet
InModuleScope -ModuleName PowerShellGet -ScriptBlock $ScriptBlock
}
```
the result will be:
```powershell
Describing [ScriptBlock]::Create
[-] Error occurred in Describe …
```

Fix using [ScriptBlock]::Create with InModuleScope.

---

Functions/Gherkin.Tests.ps1
Functions/Gherkin.ps1

Added some tests to reproduce issue #1119, and then applied a fix.
The tests are a bit long and awkward because they have to do a lot of work to arrange the test (write a temporary feature file, use Gherkin to parse it, *then* call the function under test), and I also couldn't find an easy way to compare two arrays of hashtables so the test has to walk the structure piecemeal. Any thoughts welcome about how to improve this.
Cheers,
Mike

Fix for #1119 in single column tables in Gherkin feature files

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Very small change to Invoke-Mock. Added a change to Set-Variable mocking to include a scope parameter of Global. This is intended to resolve #1107

Check scope of Set-Variable to resolve #1107

---

Functions/Assertions/Should.ps1

Refactor code slightly in `Should` command. [Documentation for ArrayList](https://docs.microsoft.com/en-us/dotnet/api/system.collections.arraylist?view=netframework-4.7.2#remarks) explicitly states that Generic.List[T] should be used instead:
> We don't recommend that you use the ArrayList class for new development. Instead, we recommend that you use the generic List&lt;T&gt; class.
This allows us to drop the `$null =` output-swallowing construct for part of the function, as `List[T]` does not emit output on `.Add()`.
Additionally, typing the List with `[PSObject]` avoids some extremely edge case problems that can occur with reboxing PSObjects that have instance members attached (such as those added via `Add-Member`).

Should: Use Generic.List[PSObject] instead of ArrayList for $inputArray

---

Functions/Gherkin.ps1

Fixes #1149
It appears that at one point, there was a variable named $StepFiles and
it was used to report how many step files from which step definitions
were loaded when displaying Verbose output. At some later time,
$StepFiles was removed and inlined into the foreach loop.
This commit restores the $StepFiles intermediate variable so that the
proper verbose output is displayed.

Fix #1149: Correctly report number of found step files

---

Functions/Environment.ps1
Functions/It.ps1
Functions/Output.Tests.ps1
Functions/Output.ps1
Pester.Tests.ps1

Fixes #1101
The issue is that when the environment variable `LANG` is set to `C.UTF-8` on Unix systems, which has now become the default for Ubuntu 18 (and it also the case for AppVeyor's `Ubuntu` image), then PowerShell's hashtable keys access is case sensitive, see [this](https://github.com/PowerShell/PowerShell/issues/7761) PowerShell issue (which will only get fixed in 6.2) due to the way .Net Core respects this culture as being 'invariant'.
This PR ensures that hashtable key casing inconsistency in Pester get fixed so that Pester still works in such environments.
Thanks @ffeldhaus for debugging this issue and providing the relevant details to avoid the symptoms of this bug

Make hashtable key access be consistently cased to prevent symptom of PowerShell bug on Unix systems where LANG is set to C.UTF-8

---

Functions/TestResults.Tests.ps1

Enabling tests that already work on all platforms instead of running them just on Windows only, only one small adoption had to be made.
On non-Windows, the `ComputerName` environment variable is not present, instead call the `hostname` binary, which returns the same info but is present on all platforms. Please use a whitespace-ignoring diff since I had to decrease indentation due to the removed if condition, after that the diff is a 1-liner in line 128

Enable TestResults.Tests.ps1 tests on all platform because they can be made to work on all platforms

---

Functions/Coverage.Tests.ps1
Functions/Coverage.ps1
Functions/Output.ps1
Pester.psm1

Per #731, introduce better support of PowerShell classes
- allow to filter on class names when asking for coverage
- provide class of each commands in coverage report

Better support of PowerShell classes in coverage

---

Functions/SetupTeardown.Tests.ps1
Functions/SetupTeardown.ps1

Using named parameter for ScriptBlock in setup and teardown blocks fails due to hardcoded pattern of `<keyword> {`.
This works:
```
BeforeEach {
$testVariable = 'From BeforeEach'
}
```
This fails:
```
BeforeEach -ScriptBlock {
$testVariable = 'From BeforeEach'
}
```
This PR updates the setup block-parser to allow both scenarios in order to fix  #1140

Add support for ScriptBlock-parameter in setup blocks

---

Functions/TestRegistry.ps1

Removes the -Force parameter from New-Item because it deletes the folder while the other Pester instance is using it, resulting in errors when multiple parallel instances of Pester are running.
Fix #1181

Fix error in parallel TestRegistry

---

Functions/Gherkin.Tests.ps1
Functions/Gherkin.ps1

As described in #360 it does not make any sense to execute the next steps of a scenario if the current step fails or is inconclusive.
(A step is a Given/When/Then clause.)
(Also with the current pull request Pester should behave more like Cucumber.)

Stop execution of scenario if one step failed/inconclusive (#360)

---

Functions/Coverage.Tests.ps1
Functions/Coverage.ps1
Pester.psm1

Using `-CodeCoverage *` includes test coverage for Pester Tests (`*.tests.ps1`) by default which is rarely useful information. This PR changes the behaviour to exclude Pester Tests if not specifically specified using a path that ends with "*.test.ps1" or a specific test-filename.
Fixes #1014
I could think of three possible solutions to this feature:
1. Introduce a new switch like `-IncludeTestsInCoverage` in `Invoke-Pester`. That would require more changes and make `Invoke-Pester` even more complex while still not being able to activate it for a specific path if you're using multiple paths/coverageinfo in a single `Invoke-Pester` call. Decided to skip this.
2. (**Initial implementation**) Exclude/Include Pester Tests based on the path provided. Since you can specify an array of …

Exclude Pester Tests from CodeCoverage by default

---

Functions/Gherkin.ps1
Pester.psm1

The pull requests removes - deprecated in the Pester v4 - the Quiet parameter.

Remove the Quiet parameter

---

Functions/Output.ps1
Functions/PesterState.Tests.ps1
Functions/PesterState.ps1
Functions/TestsRunningInCleanRunspace.Tests.ps1

Fix #885 
Write-PesterResult checks for strict mode before setting the result
value for Pending, Skipped and Inconclusive
AddTestResult sets Pending, Skipped and Inconclusive as Failed in strict
mode
AddTestResult sets the ErrorId accordingly to PesterTestPending,
PesterTestSkipped and PesterTestInconclusive instead of plainly to
PesterTestInconclusive
Add tests

WIP: Enforce test failure in non-passing results in strict mode

---

.gitignore
Functions/Context.Tests.ps1
Functions/Context.ps1
Functions/Describe.Tests.ps1
Functions/Describe.ps1
Functions/It.Tests.ps1
Functions/It.ps1

Fix #496 
Add new exceptions and clarify exception wording when a parameter to It, Describe, or Context is missing. Clarify for the use whether a name or script block is missing.

Add a new exception and clarify exception wording to It, Describe, and Context

---

Functions/Output.ps1
Functions/TestDrive.Tests.ps1
Functions/TestDrive.ps1

Under some circumstances, it appears that the delete method `FileInfo/DirectoryInfo` will throw which causes test failures. This change adds an invocation of  Remove-Item as a last-ditch effort to remove a symlink when the items' Delete method fails. I've also enabled the commented out tests for symlink removal under the appropriate circumstances by calculating whether the user is elevated on Windows. On non-Windows, symlink creation does not require elevation.

WIP: Improve logic for removal of symlinks during TestDrive tear down.

---

Functions/Gherkin.Tests.ps1
Functions/Mock.Tests.ps1
Functions/Mock.ps1

Allow aliases in Parameter Filters blocks

---

Pester.psd1

The function Invoke-GherkinStep should not be exported. The previous exclusion of it #948 is inconsistent so that pull request corrects that.

Remove Invoke-GherkinStep from exported functions

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Add alias for extension-less external commands in windows

---

Functions/Coverage.Tests.ps1
Functions/Coverage.ps1

Fix #1242 
Fixes incorrect Code Coverage report counters when there are multiple packages in the report.

Fix incorrect Code Coverage report counters (#1242)

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Ast parsing

---

signModule.ps1

Fixes a misspelling in `signModule.ps1`: where the check for duplicate thumbprint(s) is performed, the property to enumerate over the array of certifiates should be `.Length`.

Fix .Length mispelling in duplicate certificate thumbprint check in signModule.ps1

---

Pester.psd1

When this isn't specified, powershell loads the module when looking for unknown commands.

Adding empty CmdletsToExport specification.

---

Functions/Assertions/Be.Tests.ps1
Functions/Assertions/Be.ps1
Functions/Output.Tests.ps1

I removed the arrow in the output of string comparison. 
`Fix #1263 `

remove the arrow in the output of string comparison.

---

Functions/Output.ps1

Added regex statements to filter out Invoke-LegacyAssertions from error messages. 
Wasn't able to write tests for this. Could you provide me with assistance in regards to this?

WIP: Added regex to filter out ErrorLines.

---

Functions/Environment.Tests.ps1
Functions/Environment.ps1
Functions/TestDrive.Tests.ps1

special case macOS to use /private/tmp which is the real folder path
otherwise, use GetTempPath() so that on Windows it returns the long path
On macOS, the `/tmp` path is a symlink to `/private/tmp`, this causes problems in tests that create a test file and later tries to validate the path:
```powershell
$testPath = Join-Path $TestDrive "foo"
...
$realPath | Should -BeExactly $testPath
```
This fails as $testPath will be something like: `/tmp/foo` but the real file path returned from some cmdlet or .NET API will be `/private/tmp/foo`.
On Windows, the problem is that `$env:TEMP` which is used to construct the TestDrive path uses the 8.1 path syntax.  So on AzDevOps, the user is called `VSSADMINISTRATOR` so `$env:TEMP` is `C:\Users\VSSADM~1\AppData\Local\Temp\` but similar to macOS where a …

Use real path to temp path on macOS and GetTempPath() otherwise when constructing TestDrive

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Fix #1291 
This is a small fix to to the 'New-BlockWithoutParameterAliases' function. When a function definition was passed to -ParameterFilter and internally passed to 'New-BlockWithoutParameterAliases', the AST would fail because it was expecting a true scriptblock, so the AST was in a different location than expected.
It now checks to see if the passed scriptblock is a FunctionDefinitionAst or ScriptBlockAst and handles the AST appropriately.
Tests included.

Fix function definition in parameter filter

---

Functions/Mock.ps1

Listed all built-in readonly and constant variables that are defined in PowerShell 5 and 6 and added them to conflicting names list.
Related #1292 #1290

Add list of all built-in readonly and constant variables

---

Functions/Mock.ps1

Powershell v2 includes sorrounding spaces as part of script block on ToString, that made sorting to default and non-default mocks stop working because the formatter tool added spaces around `{ $True } `.
Fix #1303

Fix default mock sorting to ingore spaces in default scriptblock

---

Functions/Output.ps1
new-runtimepoc/Pester.Runtime.psm1
new-runtimepoc/Pester.Runtime.ts.ps1
new-runtimepoc/ReloadAndInvokePester.ps1

The original runtime executed the file twice and tried to match the code based on positions, this allows for code that is scattered among the tests to still run and have effects. This is the only upside. The downsides are that you need to make sure that block generators, test generators and test case generator functions run twice in the same way, because otherwise you'd get different amount of tests, and so on. In this PR I move from the file based execution to the generate and run execution (the first model). 
This also isolates the discovery and run code better because now they don't need to share the same function and same scoping concerns.

New new runtime

---

Functions/TestResults.Tests.ps1
Functions/TestResults.ps1

If you create a nunit log, the reason for skipping or a pending test is not persisted, but the schema seems to allow this, and we would like to keep the information in our logs.
The nunit schema allows for a reason to be associated with a test which is skipped or marked pending (or inconclusive). While the current behavior provides a way to emit a reason for skipping or pending, that is only written to the console and not persisted. This PR ensures that those reasons (if provided) will make it into the nunit log.

Add support for logging the reason if a test is skipped or marked pending

---

Pester.psm1

`Set-ScriptBlockHint` is called in user scope and it's not a publish function so it's not found so instead I am passing the object as parameter to make it available. 
Fixes #1370

Invoke Set-ScriptBlockHint indirectly

---

Functions/Output.Tests.ps1
Functions/Output.ps1

Pester crashes on exceptions with null error messages. This PR fixes the problem by adding an additional check in the code that "unwinds" the stack trace and error messages.
I do not believe there is an open issue for this problem on github.

Handle when exceptions have no error messages.

---

Functions/Assertions/Be.Tests.ps1
en-US/about_Should.help.txt

Adding documentation about existing support for array comparison in the `-Be` operator.
This PR fixes the `about_Should.help.txt` as requested in #1157. 
This also includes a pester test of the specific example added, showing that arrays with similar values will not pass assertion if the values are in different indexes .
If this PR is accepted the [corresponding Wiki page](https://github.com/pester/Pester/wiki/Should#be) will be updated for this change to the Help.

Add an Example of Should Be with an Array

---

.appveyor.yml

This new image has PS 6.2 in it, in contrast to the old image that had PS 6.1 in it.
Since PS 6.1 is going out of support this month, there is no point keeping the old image as well, therefore it's just a replacement.
Unfortunately, it seems 1 test does not work in PS 6.2, it errors out on this line of code and can be reproduced locally:
https://github.com/pester/Pester/blob/c300092040f837666cd98de919f187920f387cae/Functions/TestDrive.Tests.ps1#L231
```pwsh
$null = New-Item -Type SymbolicLink -Path TestDrive:/test/link1 -Target TestDrive:/d1
New-Item : The filename, directory name, or volume label syntax is incorrect : 'C:\windows\system32\TestDrive:\d1'
At C:\Users\christoph.bergmeiste\git\Pester\Functions\TestDrive.Tests.ps1:231 char:21
+ ...     $null = New-Item -Type SymbolicLink …
```

Upgrade AppVeyor image for PS Core test to 'Visual Studio 2019' to upgrade PS Core version used in tests from 6.1 to 6.2

---

Examples/Gherkin/HookTag.Steps.ps1
Examples/Gherkin/HookTag.feature
Functions/Gherkin.Tests.ps1
Functions/Gherkin.ps1

There was an incorrect variable used in `Invoke-GherkinHook` function (in `Gherkin.ps1`) for accessing hook's script - instead of an actual hook object (`$GherkinHook`), a hook's name was given (`$hook`).
This only happened for hooks with tags.
This has now been fixed and a unit test was added.
I don't believe there was any issue reported for this.

Fixed incorrect variable used for hooks with tags in Invoke-GherkinHook.

---

Functions/Coverage.Tests.ps1
Functions/Coverage.ps1
Pester.psm1
azure-pipelines.yml

- Fix missing attributes in the JaCoCo report so it can be processed by Codecov.io.
- Add new parameter `CodeCoverageOutputFileEncoding` to cmdlet `Invoke-Pester` so that the user can change the encoding.
Since this repository have enabled format on save a few whitespace changes was introduces as well.
I can update the WIki once this PR is through. 
- Fixes #1419
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pester/pester/1420)

Fix JaCoCo report so it can be processed by Codecov.io

---

Functions/Assertions/Should.ps1
Functions/Mock.ps1
new-runtimepoc/Pester.Mock.RSpec.ts.ps1

Forces should to fail on assertion failure when in mock param filter irrespective of Should preference to keep scenario that throws in ParameterFilters working.
Partial fix #1409

Throw on should failure in mock parameter filter

---

Functions/TestResults.Tests.ps1
Functions/TestResults.ps1

…which may occur with PowerShell 7
If the failure message contains an escape sequence (which can happen with PowerShell 7, and the results are going to be serialized to an Nunit file, you may see something like this:
```
MethodInvocationException: /Users/jimtru/src/github/forks/JamesWTruher/Pester/Functions/TestResults.ps1
Line |
591 |             $xmlWriter.WriteElementString('message', $TestResult.FailureMessage)
|             ^ Exception calling "WriteElementString" with "2" argument(s): "', hexadecimal value 0x1B, is an invalid character."
```
and the xml file created is partial. The escape in the message is not valid for serialization
This escapes the escape character ([char]27) to `&27;`

Handle the case when the failure message contains an escape sequence

---

Functions/Assertions/Set-TestInconclusive.ps1
Functions/Assertions/Should.ps1
Functions/Context.ps1
Functions/Describe.ps1
Functions/Get-ShouldOperator.ps1
Functions/Gherkin.ps1
Functions/GherkinHook.ps1
Functions/GherkinStep.ps1
Functions/In.ps1
Functions/It.ps1
Functions/Mock.ps1
Functions/New-Fixture.ps1
Functions/SetupTeardown.ps1
Functions/TestDrive.ps1
Pester.psm1

Comment based help in source has several .LINK problems. 
- URLs point to old pester wiki
- Several lines of commands under one .LINK entry leading to incorrect formatting
- Some commands are missing .LINK entries for their online version of help. 
See discussion https://github.com/pester/docs/issues/8
Not sure if this is finished. Unsure if each .LINK entry under a command should be to the online resource or left as plain text. Eg: 
.LINK 
Context
.LINK
https://pester.dev/docs/commands/Context

Fix Get-Help links

---

Functions/Context.ps1
Functions/Describe.ps1
Pester.psm1

Run files by pressing F5. On F5, or script invocation it will run Invoke-Pester on the containg file. It will also save it's path and execution time to prevent multiple top-level Describe / Contexts from running the whole file again.

Run files interactively

---

Functions/Context.ps1

I recently upgraded to the latest version of Pester and while debugging some of my tests were failing with below
New-PesterState : Cannot process argument transformation on parameter 'SessionState'. Cannot convert the "SessionState" value of type "System.String" to type "System.Management.Automation.SessionState".
At C:\Program Files\WindowsPowerShell\Modules\pester\4.10.1\Functions\Context.ps1:88 char:128
... '] .) -TestNameFilter $null -TagFilter @() -SessionState SessionState
It seems that a bug was introduced with Session state hints (#1169) in the change to Context.ps1 (   https://github.com/pester/Pester/commit/d25ff9f34b1fb160df096cc7101efdd8a06cbd43#diff-d4fc7a10c374cf6c159f443304feb3e4)

sessionstate variable is not being passed correctly in Context.ps1

---

Functions/Output.ps1

For the desktop version of Powershell, when getting the exception
message, there would be 3 lines: the exeception name and message, any
parameter name, and then the inner exception type (and first line
message):
```
<Exception Name>: <first message line>
Parameter: <param name>
<Inner Exception Name>: <first inner exn line>
```
But, in PowerShell Core (7.0?), the output looked like this:
```
<Exception name>: <first message line> (Parameter '<param name>')
<Inner Exception name>: <first inner exn line>
```
This commit detects whether the first message line matches a regex that
matches the parenthesized parameter name in the first message line, and
if so, splits the line into two. This "normalizes" the message lines
between PowerShell Desktop and PowerShell Core.

Fixes Convert-FailureLines for Core vs. Desktop PS

---

build.ps1
src/Pester.Runtime.psm1
src/functions/Mock.ps1
src/functions/Pester.SessionState.Mock.ps1
test.ps1
tst/functions/Mock.Tests.ps1

Remove rewriting the scriptblock, and instead define the variables that would otherwise be bound in above scope. 
This allows both Mock and ParameterFilter to be debugged. And allows usage of aliases in the ParameterFilter. 
This prevents usage of conflicting parameters names direcly in the ParameterFilter, a variable prefixed with _ needs to be used instead. This is a small sacrifice to make, and there is a "warning" in the log. 
Fixes #1297

Debug mocks

---

src/Pester.RSpec.ps1
src/csharp/Pester/Test.cs

Null the properties that we don't need on the result object because they cannot be hidden by removing psobject props. 
Fix #1510

null non-public props

---

Functions/In.ps1

Correctly capitalize the `path` and `execute` parameters of `In` function.

Capitalize parameter names of In function

---

src/Pester.RSpec.ps1
src/Pester.ps1
src/csharp/Pester/Run.cs
src/csharp/Pester/ToStringConverter.cs
src/functions/Output.ps1
src/functions/Pester.SafeCommands.ps1
src/functions/TestDrive.ps1
src/functions/TestRegistry.ps1
src/functions/TestResults.ps1
tst/functions/Pester.TestDrive.ts.ps1

Teardown TestDrive and TestRegistry only when they still exist, but don't fail when someone else already removed them, possibly a child Invoke-Pester running inside of this test.
Fixes #1524

Fix TestDrive and TestRegistry teardowns when already teared down

---

README.md
src/Pester.Runtime.psm1
src/csharp/Pester/Factory.cs
src/functions/Output.ps1
src/functions/Set-ItResult.ps1

Resolves Set-ItResult not working correctly

[v5] Repair Set-ItResult

---

src/functions/Mock.ps1
src/functions/Pester.SessionState.Mock.ps1
tst/Pester.Mock.RSpec.ts.ps1
tst/functions/Mock.Tests.ps1

Fix mock counting and cleanup when ModuleName is used.
Fix #1533
Fix #1534

Fix cross module mock

---

src/functions/Pester.SessionState.Mock.ps1
tst/Pester.Mock.RSpec.ts.ps1

Fix verifiable mocks counting to not return all behaviors when at least one is verifiable.
Fix #1539

Fix verifiable mocks counting when there are multiple behaviors

---

src/csharp/Pester/Configuration.cs
tst/Pester.RSpec.Configuration.ts.ps1

Fixes #1548
As described in the issue, there are cases where  the cast fails for a valid object array. Since very object has to implement `.ToString()`, we can do the conversion ourselves. This way the behaviour will be more PowerShell-y.
Can you point me at a good place for a unit test for that? The xunit test project don't seem to be run in CI btw.

Make StringArrayOption property perform object[] to string[] transformation automatically in a similar way how PowerShell would do it

---

Functions/Assertions/HaveParameter.Tests.ps1
Functions/Assertions/HaveParameter.ps1

Added `-Alias` to `| Should -HaveParameter`
This will check if the list of aliases of the parameter contain the string the test is trying to assert

Added parameter for Alias in HaveParameter

---

src/Pester.ps1
src/functions/assertions/Should.ps1

This Pull Request enables most of the syntax for should to maintain backwards compatibility.
e.g.  
~~~PowerShell
1 | should -be 1  # This works
1 | should be 1   # This works!
~~~

Should work

---

src/functions/assertions/Should.ps1

Improved Should Error Experience
As requested, this code will improve the user experience around breaking changes to should in v5.

Adding error message when incorrect should format is used.

---

src/Pester.ps1

This used to be part of another parameter set. It should not be mandatory in Legacy parameter set.

Make OutputPath of NUnit not mandatory

---

README.md

As requested by @nohwnd (in issue #1218), this pull request describes the mapping of v4 Legacy parameters to the configuration object. I also noticed that the *PassThru* parameter was missing from the Simple interface, so that mapping was added to that table.
There are also minor 1 line markdown linter adjustments.

(doc): Add Legacy v4 parameter mapping to config object in README.md

---

src/Pester.Runtime.psm1
src/functions/Output.ps1
tst/Pester.RSpec.ts.ps1
tst/Pester.Runtime.ts.ps1
tst/functions/GlobalMock-B.Tests.ps1

Push the whole execution one scope down to cleanup the variables and functions defined in BeforeAll correctly.
Fix #1624
Fix #1596
Fix #1579

Fix basic scoping of BeforeAll

---

docs/Examples/Planets/Get-Planet.Tests.ps1
docs/Examples/Planets/Get-Planet.ps1

Fixed the `Get-Planet` example to use a `BeforeAll` block where we dot-source the `Get-Planet.ps1` script, by following the examples provided over here https://jakubjares.com/2020/04/11/pester5-importing-ps-files/ . Also removed the PowerShell v2 comparability part, since from version 5 onwards only PowerShell v3 and higher is supported. 
This one was a bit of a pain as a **Pester** beginner, to get the first example up and running.
Fixes #1631

Fixes #1631 - Updated docs Planets example to work with Pester v5

---

README.md

Add `FullNameFilter` and `PassThru` parameters to Simple interface parameter list in README.md
It seems from the code, that `FullNameFilter` is a Simple Interface parameter, so added it to the list and table.
Also `PassThru` is added to the list.

Add FullNameFilter and PassThru parameters to Simple interface parameter list

---

src/Pester.Runtime.psm1
src/csharp/Pester/Test.cs
src/functions/Output.ps1
src/functions/TestResults.ps1
tst/Pester.RSpec.Nunit.TestResults.ts.ps1

Fix #1573 
Fix #1612
It will replace the Parameter tokens in the test names with the parameter values if provided. If no replacement has taken place, the current behavior will take place (put all parameters cast into [string] after the test name.
The current behavior breaks on test builds we are running with parametersets containing a huge array of hash tables, as they will produce test names with "System.Collections.Hashtable System.Collections.Hashtable ..." at the end, making both the result file very big and break the parser eventually. (apart from the fact it makes the results unreadable)

fix formatting for Nunit parameterrized tests

---

BUILD.md
src/functions/Mock.ps1
src/functions/Pester.SessionState.Mock.ps1
tst/functions/Mock.Tests.ps1

Fixes #1655 
Pester has a C# Solution which requires .Net Framework SDKs and Developer Packs
in order to compile. The targetted frameworks can be found in
`src\csharp\Pester\Pester.csproj`.  This commit adds instructions for where to
download these files from.
Previously Should -Invoke would ignore a negative expectation i.e. Should -Not
-Invoke.  This commit updates the Should-Invoke and Should-InvokeInternal
functions to pass through the Negation and then change the error raising
behaviour.  In particular, using -Not should have the opposite effect of if
it was not negated. That is, if it raised an error, then the negated expectation
would not raise an error, and vice versa.
This commit also adds tests for using -Not.
Note that using -Not and -ExclusiveFilter is not a valid combination …

(GH-1655) Add support for "-Not" to "Should -Invoke" tests

---

src/csharp/Pester/Configuration.cs

A clean build of the c# Pester project returns a warning due to an unused variable.
`Configuration.cs(791,28): warning CS0169: The field 'RunConfiguration._strict' is never used [/workspaces/Pester/src/csharp/Pester/Pester.csproj`
This PR removes the unused variable.

Fix unused variable build warning

---

src/Pester.Runtime.psm1
src/csharp/Pester/Block.cs
src/csharp/Pester/Test.cs
src/functions/Context.ps1
src/functions/Describe.ps1
src/functions/It.ps1
src/functions/Output.ps1
tst/Pester.RSpec.Configuration.ts.ps1
tst/Pester.Runtime.ts.ps1
tst/testProjects/BasicTests/folder1/file1.Tests.ps1
tst/testProjects/RerunFailed.tests.ps1

"Run Test" in VS Code doesn't work for running a single test which contains multiple lines to define testcases. The issue is caused by differences in how VS Code would identify the line number for a test compared to Pester's logic. Pester uses the start of scriptblock as the line number, while VS Code uses the line of `It`. VS Code's approach is preferred going forward as it's more consistent with other scenarios like describe, context and tests without testcases as well as being easier for an end user. 
```
It "Test with multiline testcases" -TestCases @(
@{Value = 1}
@{Value = 2}
) {
1 | Should -Be 1
}
}
```
This PR changes the linefilter-check to use a new "StartLine" property in Pester-objects of type Block (Describe/Context) and Test (It) which stores the location of the function …

Fix line-based filter for tests with multiline testcases

---

src/Format.psm1
tst/Format.Tests.ps1

Add `...` at the end of arrays that are longer than 10 items when formatting with Format-Nicely. 
Related #1668

Add basic elipsis to indicate the array was shortened

---

.vscode/settings.json
src/Pester.ps1
tst/functions/assertions/PesterThrow.Tests.ps1
tst/functions/assertions/Should.Tests.ps1

The command ``SHOULD -ERRORID:X`` should work all right without an explicit ``-THROW``.  Restores #132.  Fixes #1607.
Should switches should not be mandatory per #132.

Make switches not mandatory

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/library-scripts/common-debian.sh
.gitattributes
src/csharp/Pester/Pester.csproj

This PR adds devcontainer-configuration to the project. The devcontainer provides an isolated docker container to develop, build and test Pester. Using VSCode + "Remote - Container" extension, this environment is automatically loaded and seamless to the user. This helps contributors get up and running quickly with the required build tools like .NET Core 3.1 SDK. See linked issue for more information.
This first edition of the devcontainer is a lightly customized version of the [dotnetcore ](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dotnetcore/.devcontainer) sample container provided by Microsoft as it already includes .NET Core SDK 3.1 and PowerShell 7.0.3. The PR also adds a nuget-reference to  [Microsoft.NETFramework.ReferenceAssemblies](https://www.nuget. …

Add devcontainer to project

---

src/functions/TestResults.ps1
tst/Pester.RSpec.Nunit.TestResults.ts.ps1

Fix #1662 
Tests the ShouldRun property of a test result to determine if it was included or excluded from the run using tag or exclude tag.
Added two new tests to demonstrate the fix. Looking for feedback on situation where describe block is filtered out so the NUnit report has a test suite reported as succeeded but contains no results or test cases.

Filter excluded tests from NUnit results

---

src/functions/Pester.SessionState.Mock.ps1
tst/functions/Mock.Tests.ps1

Updates `Should -Invoke` to always throw on pipeline-input or when `-ActualValue` is provided. Previously accepted a string through which would override `-CommandName`. Since `-CommandName` is mandatory the pipeline only worked in this confusing scenario:
```
"functionB" | Should -Invoke -CommandName "functionA"
```
After this PR, valid usage is:
```
Should -Invoke functionA                # + additional parameters for -Invoke
Should -Invoke -CommandName functionA   # + additional parameters for -Invoke
```
Fix #1696

Remove pipeline support from Should -Invoke

---

src/functions/Coverage.ps1

___Note: This PR contains the same bug fix as #1494, but is based on the `v5.0` branch instead of `master`.___
---
Pester generates all breakpoints using a combination of line number and column number. PowerShell does not trigger breakpoints on the proxy function constructs described in #1028 when initiated using both line and column number, but it does when using line number only. This appears to be a bug within PowerShell itself, as the behavior can be replicated outside of Pester like so:
```powershell
$ProxyMetadata = New-Object System.Management.Automation.CommandMetaData (Get-Command Write-Output)
@"
Function Write-FancyTestOutput {
$([System.Management.Automation.ProxyCommand]::Create($ProxyMetadata))
}
"@ | Out-File $PWD\Write-FancyTestOutput.ps1
$ast = …
```

Fixes #1028 - Code Coverage for proxy functions/steppablePipelines (updated to v5.0.3)

---

Functions/Coverage.ps1

Pester generates all breakpoints using a combination of line number and column number. PowerShell does not trigger breakpoints on the proxy function constructs described in #1028 when initiated using both line and column number, but it does when using line number only. This appears to be a bug within PowerShell itself, as the behavior can be replicated outside of Pester like so:
```powershell
$ProxyMetadata = New-Object System.Management.Automation.CommandMetaData (Get-Command Write-Output)
@"
Function Write-FancyTestOutput {
$([System.Management.Automation.ProxyCommand]::Create($ProxyMetadata))
}
"@ | Out-File $PWD\Write-FancyTestOutput.ps1
$ast = [System.Management.Automation.Language.Parser]::ParseFile( `
"$PWD\Write-FancyTestOutput.ps1", `
[ref]$null, `
[ref]$null `
)
$LineNumber = 0 …
```

Fixes #1028 - Code Coverage for proxy functions/steppablePipelines

---

src/functions/assertions/Should.ps1
tst/Pester.RSpec.ts.ps1

Throw when legacy syntax is used

---

README.md
src/Pester.ps1
src/csharp/Pester/Configuration.cs
src/functions/Output.ps1
tst/Pester.RSpec.Configuration.ts.ps1
tst/Pester.RSpec.Output.ts.ps1

VSCode's [problem matcher](https://code.visualstudio.com/Docs/editor/tasks#_defining-a-problem-matcher) used to report failed Pester-tests in previous versions using a regex-pattern and task.json setup included in the vscode-powershell extension. New format for test output introduced in Pester v5 broke this feature for this version. See powershell/vscode-powershell#2931
This PR and a related PR in vscode-powershell will restore the feature by providing a similar output format to previous versions when using tasks in VSCode.
When test-tasks are configured to continue beyond the first failed assertion (configuration option `[PesterConfiguration]@{Should=@{ErrorAction="Continue"}}`), all failed assertions will be get it's own failed-test output. This way VSCode can detect and show a …

Add support for VSCode problem-tracking for failed assertions

---

src/Pester.psd1
src/Pester.psm1
src/functions/New-Fixture.ps1
tst/functions/New-Fixture.Tests.ps1
tst/functions/New-Fixture.ts.ps1

The `New-Fixture` function available in previous Pester versions was not migrated to Pester v5 in the first releases. This PR re-introduces the feature with the following improvements:
- Pester 5 compliant
- Updated sample/template code to be testable
- Improved parameter validation:
- Now also strips .psm1 from Name in addition to the .ps1 like previous versions
- Validates no whitespace in Name as it's not allowed in function names
- A P-test has also been added to validate the generated script and test code (previous todo comment in Pester v4 tests).
Fix #1723

Re-implement New-Fixture in Pester v5

---

src/functions/Mock.ps1
tst/functions/Mock.Tests.ps1

The default Args-value for Mocks of type advanced functions or cmdlets, `$null`, can cause a `ParameterBindingException` when a advanced function/cmdlet is mocked by another advanced function.
The args-value is converted to an object array (`@($null)` ) before being splatted to the mock during execution. That means a `$null` value is actually sent to the mock as an argument. Advanced functions/cmdlet doesn't support arguments by default, so unless a unused parameter is available (for positional binding), the following exception can be thrown:
`ParameterBindingException: A positional parameter cannot be found that accepts argument '$null'`
Changing the default Args-value to an empty array solves the problem. During mock execution, the value is always being casted to `[object[]]`, so using …

Fix default Mock Args-value

---

src/Pester.Runtime.psm1
src/functions/Output.ps1

This PR enables Pester to print enabled filters during a run when using Detailed or Diagnostic output level.
The filters are shown at the start of discovery. Example:
> Discovery: Starting test discovery in 2 test containers. 
> 
> Starting discovery in 2 files.
> **Filter 'Tag' set to ('Function').
> Filter 'ExcludeTag' set to ('Ignore', 'Stuff').
> Filter 'Line' set to ('C:\tests\file1.Tests.ps1:37', 'C:\tests\file12.Tests.ps1:371').**
> Discovery: Discovering tests in /workspaces/Pester/demo.ps1 
> Discovering in /workspaces/Pester/demo.ps1.
> Found 3 tests. 13ms
> Discovery: Found 3 tests in 17 ms 
> Discovery: Processing discovery result objects, to set root, parents, filters etc. 
> Filter: ('Set-BuildRunToCI' Unit Tests) There is 'Ignore, Stuff' exclude tag filter. 
> ...
Known …

Print active filters in Detailed/Diagnostic output

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/commandhelp_issue.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

PR suggest changes to the github templates used for the Pester repo. In replace of on large issue template, a use will get the choice between one per issue type:
- Bug report
- Feature request/idea
- Documentation issue
- General/blank issue for anything else
A link to the website for community support is also added
The text is also updated with new documentation-links, tips and updated script for collecting environment data (autodetects using currently loaded `Invoke-Pester`cmdlet).
The pull request template is also updated with new links and a checklist for common steps.
Fix #1732

Update github templates

---

.github/PULL_REQUEST_TEMPLATE.md

Removes requirement for running local tests as discussed in https://github.com/pester/Pester/pull/1743#issuecomment-717965537

Removed test-step in PR template

---

src/Pester.Runtime.psm1

Join paths on assignment so we have ExpandedPath set correctly in case of crash.

Fix joining fallback ExpandedPath

---

src/Pester.Runtime.psm1
tst/Pester.RSpec.Output.ts.ps1

Fix output to screen in Detailed mode for each block when -ForEach is used. 
Fix #1759 

Fix output when -ForEach is used with a block

---

.github/ISSUE_TEMPLATE/bug_report.md

I know it was my idea to add the label but I find it unnecessarily noisy. Just having Feature and Documentation labels for the other types of issues is enough.

Remove Bug label from issue

---

src/functions/New-Fixture.ps1
tst/functions/New-Fixture.Tests.ps1
tst/functions/New-Fixture.ts.ps1

Updated New-Fixture with:
- New template that fails by default as discussed in #1766 .
- Moved `-Name` to be first positional parameter to enable usage like `New-Fixture "Get-MyNewFunction"`. `-Path` already defaults to current directory, so no need to be first.
Fix #1766

Updated New-Fixture template

---

tst/Pester.RSpec.ts.ps1

Testing the scenario in issue. Which also tests that pass script parameters to both Run and Discovery when no -ForEach is used.
Related #1770

Test for passing params to It wihout any foreach

---

src/Pester.ps1
src/functions/Context.ps1
src/functions/Describe.ps1
src/functions/InModuleScope.ps1
src/functions/It.ps1
src/functions/New-MockObject.ps1
src/functions/Pester.SessionState.Mock.ps1
src/functions/Set-ItResult.ps1
src/functions/assertions/Should.ps1

Added missing markdown codeblocks to examples where code includes a blank line. This is to help pester.dev show codeblocks correctly.
Also updated some help examples using ` ```ps` to ` ```powershell`.
Fix #1781 

Added missing codeblock to help examples

---

src/Pester.RSpec.ps1
src/Pester.ps1
src/en-US/about_Pester.help.txt
src/functions/Context.ps1
src/functions/Describe.ps1
src/functions/Get-ShouldOperator.ps1
src/functions/InModuleScope.ps1
src/functions/It.ps1
src/functions/New-Fixture.ps1
src/functions/Pester.SessionState.Mock.ps1
src/functions/SetupTeardown.ps1
src/functions/TestResults.ps1
src/functions/assertions/Should.ps1
tst/Help.Tests.ps1

This PR adds and updates help for exported functions.
- Add missing help:
- Update help for:
- Add missing parameter help for:
- Add tests for detecting missing help elements
Fix #1783 
Related #1634

Add missing and update help for exported functions

---

Pester.BuildAnalyzerRules/Pester.BuildAnalyzerRules.psm1
src/Pester.ps1
src/functions/New-Fixture.ps1
src/functions/Pester.SafeCommands.ps1

Fixes spelling of SafeCommand from SafeComand

Fix safecommand spelling

---

src/functions/assertions/Should.ps1
tst/functions/assertions/Should.Tests.ps1

When generating help automatically $MyInvocation is not defined and we index out of the array in the dynamic operators.

Fix index error when using Get-Command on Should

---

azure-pipelines.yml
src/Pester.ps1
src/csharp/Pester/Configuration.cs
src/en-US/about_Pester.help.txt
src/functions/TestResults.ps1
tst/Pester.RSpec.Nunit.TestResults.ts.ps1

Fix NUnit2.5 option

---

Pester.BuildAnalyzerRules/Pester.BuildAnalyzerRules.psm1
src/Pester.RSpec.ps1
src/Pester.ps1
src/Pester.psd1
src/functions/Context.ps1
src/functions/Describe.ps1
src/functions/Get-ShouldOperator.ps1
src/functions/InModuleScope.ps1
src/functions/New-Fixture.ps1
src/functions/Pester.SafeCommands.ps1
src/functions/Pester.SessionState.Mock.ps1
src/functions/Set-ItResult.ps1
src/functions/TestResults.ps1
tst/Help.Tests.ps1

Multiple edits to the command ref help. See https://github.com/pester/docs/pull/78#issuecomment-739539632

Cleanup command reference help and add online help link

---

src/Pester.ps1
src/Pester.psd1

Fixes RELATED LINKS in `Invoke-Pester` help. 
Commented placeholder for ScriptAnalyzer suppression-rule got too close to the comment-based help which resulted in this issue:
```
RELATED LINKS
https://pester.dev/docs/quick-start
https://pester.dev/docs/commands/Invoke-Pester
https://pswiki.net/invoke-pester-pester/
https://pester.dev/docs/commands/Describe
about_Pester
Currently doesn't work. $IgnoreUnsafeCommands filter used in rule as workaround
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('Pester.BuildAnalyzerRules\Measure-SafeComands', 'Remove-Variable', Justification = 'Remove-Variable can't remove "optimized variables" when using "alias" for Remove-Variable.')] 
```
Also updates examples with missing description.
- If not, use the arrow next to `Create Pull Request` to mark it …

Fix help for Invoke-Pester

---

src/Pester.ps1

Fixed a type in the examples of 'Invoke-Pester' as '$config.TestResults' does not exist.

fixed typo in the examples of Invoke-Pester

---

src/Pester.RSpec.ps1
src/Pester.ps1

Replaces non-breaking spaces (ascii code 160) with regular spaces (ascii code 32) to Fix #1820.

Replace non-breaking spaces with regular spaces

---

src/Pester.ps1
src/csharp/Pester/Configuration.cs
src/functions/Coverage.ps1
tst/functions/Coverage.Tests.ps1

Adding ability to recursively traverse sub folders to find all files to be included in code coverage. This can be turned off by setting a new configuration option (CodeCoverageConfiguration.RecursePaths) to false. I have set it to true by default as I feel that this is the default expected behavior.
I also noticed that the coverage.xml file was not fully compatible with ReportGenerator and so I updated the sourcefile names to include the relative path so the code could be populated correctly in the finished report.
This new option should be documented at the https://pester.dev/docs/usage/code-coverage
`Fix #1621` 

Fix blank code coverage 1621

---

publish/release.ps1

Fix #1839 
This fixes the issue with Chocolatey validation of the Nuget package. Amended the release to include the LICENSE file.

Fix missing LICENSE file in Nuget package (#1839)

---

src/Pester.Runtime.psm1

Using ParameterAttribute or CmdLetBinding in a parameterized testfile causes ParameterBindingException for a `$null`-value when invoked without providing any parameter-values. $Data-parameter is default null in `Invoke-File`, but is always passed to the scriptblock. This throws the error since advanced functions (testfile) don't implicitly allow arguments.
PR changes $Data to be empty hashtable by default as splatting the empty hashtable will avoid the error while not affecting the script/testfile. Similar to #1730 for Mocks and #1812 for InModuleScope.
Fix #1851

Fix default Data-value in Invoke-File

---

src/functions/InModuleScope.ps1
tst/functions/InModuleScope.Tests.ps1

Using ParameterAttribute or CmdLetBinding in InModuleScope scriptblock causes ParameterBindingException for the default when no arguments are provided. $ArgumentList-parameter is default null and is always passed to the scriptblock, which throws the error since advanced functions don't implicitly allow arguments.
PR changes $ArgumentList to be empty array by default as it won't cause the exception when not defined. Similar to #1730 for Mocks.
Fix #1809 

Fix default InModuleScope args-value

---

src/Pester.Runtime.psm1
src/functions/Describe.ps1
tst/Pester.RSpec.InNewProcess.ts.ps1

Pester 5.1 re-introduces parameterized testfiles using ContainerInfo-objects created with `New-PesterContainer`. This PR extends this effort by allowing parameterized testfiles to be called using interactive execution, ex.
`& ./SampleProject/CodingStyle.Tests.ps1 -File "build.ps1"`
Fix #1784

Fix interactive execution of parameterized tests

---

src/functions/Mock.ps1
tst/Pester.Mock.RSpec.ts.ps1

Fix conflicting name "arguments" in parameter filter

---

src/Pester.RSpec.ps1
tst/Pester.RSpec.ts.ps1

Fix how paths are resolved when wildcard is used. Ensure that we inspect all items when more than 1 resolves from a wildcarded path. But filter those expanded paths down to *.Tests.ps1 to avoid including everyting. On the other hand when just a single file is added, or the wildcard resolves to just a single item, use that no matter what the file or filetype is, to allow any file to be invoked via Pester no matter what the extension is.
Fix #1857

Fix wildcards in dirs

---

.gitignore
src/Pester.ps1
src/csharp/Pester/Coverage.cs
src/csharp/Pester/Factory.cs
src/csharp/Pester/Run.cs
src/functions/Coverage.ps1
src/functions/Output.ps1

Added Coverage to the Result object, and printing of the report to screen. The same report is reported to the CoverageObject. 
Fix #1625

Add Coverage to result object

---

src/Pester.Runtime.psm1
src/Pester.ps1
src/csharp/Pester/Configuration.cs
src/csharp/Pester/Coverage.cs
src/functions/Coverage.Plugin.ps1
src/functions/Coverage.ps1
src/functions/Output.ps1

Improve output, add percentage target so we can print green or red coverage message. Disable outputting missed commands in non-detailed output, but keep it in the result object.

Little improvements to coverage output

---

src/Pester.Runtime.psm1
src/Pester.ps1
tst/Pester.RSpec.ts.ps1
tst/Pester.Runtime.ts.ps1
tst/functions/It.Tests.ps1
tst/functions/PesterState.Tests.ps1

Initialize state in Invoke-Pester rather than using global one to allow running Pester in Pester.
Fix #1867

Initialize state in Invoke-Pester and inherit it to children

---

src/Pester.ps1
tst/Pester.RSpec.ts.ps1

The Pester 4-compliant result-object returned from `ConvertTo-Pester4Result` includes a blank version-property and not `4.99.0` as expected. PR sets the value as string-type, just like the version-property in Pester5 result-object
Fix #1786

Fix broken Version-property in Pester4Result object

---

PSScriptAnalyzerSettings.psd1

The custom "Measure-SafeCommands" PSScriptAnalyzer rule is noisy when editing files in VSCode outside of "src\\*" where it shouldn't apply.
There currently isn't a way to limit the paths where VSCode use PSSA automatically, so the rule is excluded in "PSScriptAnalyzerSettings.psd1" for now. That way, we can still benefit from automatic checks against other useful default rules.
The SafeCommands-rule can still be invoked manually using `Invoke-ScriptAnalyzer -Path ./src -CustomRulePath ./Pester.BuildAnalyzerRules/ -Recurse`
Fix #1761 

Exclude noisy Measure-SafeCommands rule by default

---

src/Pester.ps1
src/csharp/Pester/CodeCoverageConfiguration.cs
src/csharp/Pester/Factory.cs
src/functions/Coverage.ps1
src/functions/assertions/Be.ps1
test.ps1
tst/functions/Coverage.Tests.ps1

Add a coverage format specific to Coverage Gutters, to make it easy to use with Pester in VSCode and also fix some of the problems with it. Now you can specify whatever path your want covered, including the path to which coverage.xml is output, and not just a subfolder. The root is determined based on the location of coverage.xml not the common root of files, so it is static and not dynamic. 
Building on this article: https://web.archive.org/web/20201107233838/https://www.pwsh.site/powershell/2019/01/10/how-to-enable-coverage-markings-in-vscode-for-your-powershell-projects.html
Integration with the PowerShell extension Code Lens in VSCode is not done yet, because the pester integration does not have the ability to provide a custom setup script, but can be either done by a custom launch …

Coverage gutters

---

src/Pester.Runtime.ps1
tst/Pester.Runtime.ts.ps1

Fix #1848
Ensure that when there are multiple blocks in a block we don't incorrectly mark the block as Passed = $false, when one of them is not run because it is filtered out, or skipped because of the -skip parameter.

Fix setting passed on parent block when some blocks are not run

---

src/Format.ps1
src/Main.ps1
src/Pester.Runtime.ps1
src/csharp/Pester/RunConfiguration.cs
src/functions/Output.ps1
src/functions/assertions/HaveParameter.ps1
tst/Pester.RSpec.ts.ps1

Throw on failure when enabled. If you want to process the result for some reason after catching the exception, you need to use 
```powershell
$result = try { Invoke-Pester ... } catch { $err = $_ }
```
And not  
```powershell
try { $result = Invoke-Pester ... } catch { }
```
Because then the assignment will never happen and `$result` will be null.
But in such case it is better to just not enable the throwing and throw yourself based on the .Result
Fix #1843

Add option to throw on failure

---

src/Main.ps1

Disabling code coverage for -CI switch because it is rarely used, and it is slow in every version of PowerShell and won't ever be fast on v5, and v6, and older v7 unless we use some ugly hacks.
Fix #1547

CI switch does not enable CodeCoverage by default

---

src/Pester.Runtime.ps1

Fixes broken output for currently set FullName-filter. Caused by a cast to `string[][]` which seems to be a typo.
Fix #1892 

Fix output for currently set fullname-filter

---

src/Main.ps1
src/functions/Mock.ps1
src/functions/Pester.SessionState.Mock.ps1
tst/Pester.Mock.RSpec.ts.ps1

Set mocks into the module specified by -ModuleName, or when not present into the current module. This means that in script it will be set into the script, but when running InModuleScope then the module will be used.
Fix how mock resolve is done to respect the -ModuleName, and only fallback to the default script behavior when a parametrized mock in module fails and there is no default behavior. 
Remove mocks in all modules and user scope on startup to clean up after cancelled runs. 
Throw when we resolve command in Should but it is not a Hook.
Fix #1827
Fix #1878
Fix #1868

Fix mock behavior for Mock and Should -Invoke

---

src/csharp/Pester/CodeCoverageConfiguration.cs
src/functions/Coverage.ps1
src/functions/Mock.ps1
src/functions/Pester.SessionState.Mock.ps1
test.ps1

Remove the option because the new approach is always faster so there is no point in having an option to do it the old much slower way.
Also fix some minor Mock output that I did notice when writing release notes.

Remove delay bps option because it is never faster

---

src/functions/Mock.ps1

Cleanup should skip script modules without any session state because that is apparently a thing.
Fix #1921

Fix cleanup for modules with no session state

---

tst/Format.Tests.ps1

From browsing the `Format.ps1` functions, I noticed that some functions like `Join-And` and `Add-SpaceToNonEmptyString` are missing tests in `Format.Tests.ps1`. I've added some basic tests to cover these functions.
Let me know if these tests are too simple and/or don't feel the need to include them. I didn't see why not to include them :smile:. 

Added missing format tests

---

src/functions/Mock.ps1
tst/Pester.Mock.RSpec.ts.ps1

Fix module resolve when in module scope and module is force re-imported, by checking the current session state first, and only resolve module by name later.
Fix #1939

Fix module resolve when in module scope and module is force re-imported

---

build.ps1
src/Main.ps1
src/Pester.RSpec.ps1

> Also noticed that we should wrap the auto-generated pesterconfiguration-docs in a codeblock to keep it's format. Will look into that in pester-repo incl. updating the help for Hashtable-parameter to mention that all options are visible in description (no longer need to inspect).
Source https://github.com/pester/docs/pull/112#pullrequestreview-659872259
Wraps generated config-docs in markdown codeblock to keep formatting on website. Also updates some of the help text

Update New-PesterConfiguration help

---

src/functions/Get-ShouldOperator.ps1
tst/functions/Get-ShouldOperator.Tests.ps1

This PR allows positional value to used for Name in `Get-ShouldOperator` to make it more user-friendly so users can type e.g. `Get-ShouldOperator Be`

Allow positional parameter in get-shouldoperator

---

src/Pester.RSpec.ps1

Updated to reference the correct variable.  As requested in https://github.com/pester/docs/pull/114
Correcting a mistake in the documentation.  The example references $c when it should reference $config

Update Example to reference the correct variable

---

src/functions/Mock.ps1
tst/Pester.Mock.RSpec.ts.ps1

Fix session state in Should -Invoke to use the correct session state

---

src/functions/InModuleScope.ps1
tst/functions/InModuleScope.Tests.ps1

`InModuleScope` currently requires param-block to make parameters available by name (if not, only available as arguments). This PR add parameters as dynamic variables inside the scriptblock similar to how it works with mocks.
Fix #1603 

Make InModuleScope-parameters available as variables in scriptblock

---

src/Format.ps1
tst/Format.Tests.ps1

I had some time and added a fix for #1448.
`Format-Nicely` from `Format.ps1` now formats `$null` elements to `$null` in the array output.
e.g. `Format-Collection -Value @('a', 'b', 'c', $null)` -> `@('a', 'b', 'c', $null)`
The previous behaviour would omit the `$null` value.
e.g. `Format-Collection -Value @('a', 'b', 'c', $null)` -> `@('a', 'b', 'c')`
To achieve the result from the first example, I changed the implementation to not use `Select-Object`, since it removes null values, and instead use a simple loop to format each element and join back up to a comma separated string. 
I've also changed the ellipsis to indicate how many elements have been left out with `...<leftover count>` instead of just `...`. Let me know if this needs to be tweaked or its fine to keep `...`.
- If not, use …

Fixed formatting for null elements in an array

---

src/functions/Output.ps1

Fix for #1342.
Added the pester version for detailed and diagnostic view as shown below. 
This leverages a lot of the previous code from @KirkMunro in https://github.com/pester/Pester/pull/1343/files. It just excludes the ascii art and outputs the pester version(including pre-release if any) above the start message. Let me know if this should be merged and edited from that instead, I just copied over some of the relevant code into this commit. 

Added Pester version message to detailed and diagnostic output

---

src/Pester.RSpec.ps1
src/functions/Coverage.ps1
tst/CoverageTestFile.ps1
tst/Pester.RSpec.Coverage.ts.ps1

Fix coverage in `param` when there are default values.

More tracer fixes, now it's on par with the current solution

---

src/functions/Output.ps1

Provided a fix for #1967.
I've removed the `"Executing all tests in..."` Start message as shown below. Only the version is outputted at the start now. 

Removed StartMessage from output

---

build.ps1
src/Pester.psd1
tst/PesterConfiguration.Tests.ps1

Dynamically generates a ps1xml with formatdata for configuration sections in [PesterConfiguration] to ensure that all sections use list view. Currently Output and Should uses table due to less than 5 options.
```powershell
(New-PesterConfiguration).Should
ErrorAction
-----------
Controls if Should throws on error. Use 'Stop' to throw on error, or 'Continue' to fail at the end of the test. (Stop, default: Stop)
(New-PesterConfiguration).Output
Verbosity
---------
The verbosity of output, options are None, Normal, Detailed and Diagnostic. (Normal, default: Normal)
(New-PesterConfiguration).Should
ErrorAction : Controls if Should throws on error. Use 'Stop' to throw on error, or 'Continue' to fail at the end of the test. (Stop, default: Stop)
(New-PesterConfiguration).Output
Verbosity : The …
```

Add formatdata to ensure list view for all sections in PesterConfiguration

---

src/Main.ps1
src/Pester.RSpec.ps1
src/Pester.Runtime.ps1
src/csharp/Pester/DebugConfiguration.cs
src/functions/Output.ps1
tst/Pester.RSpec.Configuration.ts.ps1
tst/Pester.RSpec.Output.ts.ps1

- Removes file-specific discovery message from Detailed view. This is still available as Discovery debug-messages in Diagnostic
- Output number of tests to be executed.
- Removes redundant and noisy active tag filter debugmessages (covered in initial discovery-output in Detailed + Diagnostic), see before-image here https://github.com/pester/Pester/issues/1746#issuecomment-854043879
- Fix runtime configuration leak when using advanced configuration with `Invoke-Pester -Configuration ...`
Example of output after PR:
Diagnostic:
Fix #1552
Fix #1746 
Fix #1972

Update output for Discovery and Filter

---

Pester.BuildAnalyzerRules/Pester.BuildAnalyzerRules.psm1

New PSSA analyzer-rule to highlight usage of most `*-Object` built-in cmdlets as they can be slower than other alternatives.
Currently Information-level.
Based on https://github.com/pester/Pester/pull/1745#issuecomment-719455100

Add analyzerrule for highlighting slow *-object commands

---

src/Main.ps1
src/Pester.RSpec.ps1
src/csharp/Pester/DebugConfiguration.cs
src/csharp/Pester/OutputConfiguration.cs
src/functions/Output.ps1
tst/Pester.RSpec.Configuration.ts.ps1
tst/Pester.RSpec.Junit.TestResults.ts.ps1
tst/Pester.RSpec.Nunit.TestResults.ts.ps1
tst/functions/Output.Tests.ps1

Fix #917
I've added a `Output.StackTraceVerbosity` option with the following levels:
**None** - All Stack trace is hidden
**FirstLine** - First line of stack trace is shown
**Filtered** - Filtered lines that belong to Pester. This is default.
**Full** - All stack trace is shown
```pwsh
BeforeAll {
function Test-EvenNumber {
[CmdletBinding()]
param (
[Parameter(Mandatory)]
[int]
$Number
)
$Number % 2 -eq 0
}
}
Describe Test-EvenNumber {
Context "Even Numbers" {
It "<number> is even" -TestCases @(
@{ Number = 1 },
@{ Number = 3 },
@{ Number = 5 }
) {
param($Number)
Test-EvenNumber -Number $Number | Should -BeTrue
}
}
}
```
```pwsh
$pesterConfig = [PesterConfiguration]::Default
$pesterConfig.Run.Container = New-PesterContainer -Path C:\Users\Armaan\Documents\powershell-dev\sample.Tests.ps1 …
```

Limit output information for failed tests

---

src/csharp/Pester/GenericOption.cs
tst/Pester.RSpec.Configuration.ts.ps1

Makes the setter of Value-property in configuration options private. This is done because modifying `Value` directly won't flip the internal `_isOriginalValue`-flag used to detect whether a user has modified the option. This is important to know which values to override when merging configuration.
Fix #1971
**Possible breaking change:** Users may create their advanced configurations by modifying Value directly because it has been possible or because it can be easier in certain scenarios, ex.
```powershell
$c.Debug.WriteDebugMessagesFrom.Value += 'MyForgottenCategory'
$c.Debug.WriteDebugMessagesFrom = $c.Debug.WriteDebugMessagesFrom.Value + @('MyForgottenCategory')
```
- If not, use the arrow next to `Create Pull Request` to mark it as a draft. PR can be marked `Ready for review` when it's …

Block direct modification of Value-property in configuration options

---

src/functions/Mock.ps1
tst/functions/Mock.Tests.ps1

New attempt at debug-logging variables that may cause false matches during `Should -Invoke` due to conflict with a known parameter or alias name in the mocked command.
Fix #1873
Related #1912

Log conflicting variables in Should -Invoke -ParameterFilter

---

build.ps1
src/csharp/Pester/Tracing/ExternalTracerAdapter.cs
src/csharp/Pester/Tracing/Tracer.cs
src/functions/Coverage.Plugin.ps1
src/functions/Coverage.ps1
tst/functions/Coverage.Tests.ps1

Fix #1989
Handle cancellation without finally better. So we don't block ourselves from running next time.

Fix tracer state on cancelled Pester run with new CodeCoverage

---

src/Main.ps1
src/Pester.RSpec.ps1
src/csharp/Pester/PesterConfiguration.cs
src/csharp/Pester/TestDriveConfiguration.cs
src/csharp/Pester/TestRegistryConfiguration.cs
tst/Pester.RSpec.Configuration.ts.ps1
tst/functions/Pester.TestDrive.ts.ps1
tst/functions/Pester.TestRegistry.ts.ps1

Fix #2004 
Fix #1340
Fix #1344
Add option to disable test drive and test registry. This will make the run faster if you are not using any of those capabilities. And also will allow runs that run in restricted machines such as ones that don't have access to registry.

Add option to disable TestDrive and TestRegistry

---

src/Main.ps1
src/functions/TestResults.ps1
tst/Pester.RSpec.Coverage.ts.ps1
tst/Pester.RSpec.Junit.TestResults.ts.ps1
tst/Pester.RSpec.Nunit.TestResults.ts.ps1
tst/p.psm1

Fix throwing on missing folders for TestResults and Coverage. And improve error message for no files.
Fix #1875

Fix throwing on missing folders

---

src/functions/assertions/HaveParameter.ps1
tst/functions/assertions/HaveParameter.Tests.ps1

Fix #1890
Adds support for testing argument completers added using Register-ArgumentCompleter.

Adds support for Register-ArgumentCompleter to -HasArgumentCompleter

---

README.md
src/functions/Mock.ps1
src/functions/Pester.SessionState.Mock.ps1
tst/functions/Mock.Tests.ps1

Updates InvokeVerifiable assertion with negate support. `Should -Not -InvokeVerifiable` expects none of the defined verifiable mocks to be called and will fail if **any** were.
This PR also updates the error message to output all missed (called when `-Not`) mock behaviors. The previous error message only showed the first missing mock even though `Mock` command help says it should mention all.
https://github.com/pester/Pester/blob/56131fa2a0472918c7456e16c5c8a2e45b347ac8/src/functions/Pester.SessionState.Mock.ps1#L75-L78
Output before PR:
Output after PR:
Fix #1779
/cc @bchristie

Update InvokeVerifiable error message and add negate support

---

src/Pester.Runtime.ps1
src/functions/Context.ps1
src/functions/Describe.ps1
tst/Pester.RSpec.InNewProcess.ts.ps1
tst/Pester.RSpec.ts.ps1

Pester containers may use parameters to support data-driven test generation.
This scenario currently has the following limitations:
- Default values for parameters are available as variables in Discovery, but not in Run (test execution) unless passed using tricks like `Describe 'd1' -ForEach { myparam = $myparam}`. This makes debugging harder since `Debug Tests` in VSCode doesn't allow the user to provide `-Data ...` for the container (file).
- Default values are also not available in `*All/*Each` setup-blocks placed outside any Describe/Context-blocks. The `Describe -ForEach ..`-workaround above does not work for these root-scoped setup-blocks.
- Discovery and Run are inconsistent when using aliases for script parameters. Given a container with parameter "MyParam" which has a alias of …

Add missing container-parameters to Data

---

src/Main.ps1
src/Pester.RSpec.ps1
src/csharp/Pester/OutputConfiguration.cs
src/functions/Output.ps1
tst/Pester.Mock.RSpec.ts.ps1
tst/Pester.RSpec.Configuration.ts.ps1
tst/Pester.RSpec.Demo.ts.ps1
tst/Pester.RSpec.Output.ts.ps1
tst/Pester.RSpec.ResultObject.ts.ps1
tst/functions/New-Fixture.ts.ps1
tst/functions/Output.Tests.ps1

Fix #1364.
I've added functionality to highlight CI errors in red for ADO and GithubActions. 
This is configured from the `Output.CIFormat`, which covers the following options:
- **None** -> No CI autodetection
- **Auto** -> Autodetects CI
- **AzureDevops**
- **GithubActions**
For AzureDevops, we check the `TF_BUILD` environment variable is equal to `True`.
For GithubActions, we check the `GITHUB_ACTIONS` environment variable is equal to `True`. 
For **AzureDevops** we can use `##vso[task.logissue type=error]` to highlight the error header, and `##[error]` to highlight the messages. This ensures only the error header is reported in the build log. 
For **GithubActions**, you can only set an error, so I had to limit this to just the header, as shown below. The messages are also collapsed …

Azure Devops & Github Actions error logging

---

src/Main.ps1
src/Pester.RSpec.ps1
src/Pester.Runtime.ps1
src/csharp/Pester/FilterConfiguration.cs
tst/Pester.Runtime.ts.ps1

Fix #1992
I've included a `Filter.ExcludeLine` option. 
```pwsh
Describe "block1" { #Line 1
It "Test1" { #Line 2
$true | Should -BeTrue
}
Context "block2" { #Line 5
It "Test2" { # Line 6
$true | Should -BeTrue
}
It "Test3" { #Line 9
$true | Should -BeTrue
}
}
}
```
```pwsh
$pesterConfig = [PesterConfiguration] @{
Run = @{
Container = New-PesterContainer -Path C:\Users\Armaan\Documents\powershell-dev\sample.Tests.ps1
}
Output = @{
Verbosity = "Diagnostic"
}
}
```
Include Context block
Exclude Test2
```pwsh
$pesterConfig.Filter.Line = "C:\Users\Armaan\Documents\powershell-dev\sample.Tests.ps1:5"
$pesterConfig.Filter.ExcludeLine = "C:\Users\Armaan\Documents\powershell-dev\sample.Tests.ps1:6"
Invoke-Pester -Configuration $pesterConfig
```
Only Test 3 is run
Include Describe, Context and Test2 …

Added Filter.ExcludeLine option

---

src/functions/assertions/Should.ps1

Fixes link to the pester.dev  [Assertions page](https://pester.dev/docs/assertions/assertions) for the Should command.
Ready to merge.

Fix broken link to pester.dev assertions page

---

src/functions/assertions/FileContentMatchMultilineExactly.ps1
tst/functions/assertions/FileContentMatchMultilineExactly.Tests.ps1

Fix #1605
Added a FileContentMatchMultilineExactly assertion to case sensitively match text on multiple lines.
```
$var1 = Line one BLAH Blah blAH
$var2 = Line two BLAH Blah blAH 
$var3 = Line three BLAH Blah blAH
```
```pwsh
BeforeAll {
$matchstring = @'
$var1 = Line one blah blah blah
$var2 = Line two blah blah blah 
$var3 = Line three blah blah blah
'@
$file = Get-ChildItem -Path $PSScriptRoot/sample.txt
}
Describe "Should -FileContentMatchMultiline" {
It "Case insensitively match all lines" {
$file | Should -FileContentMatchMultiline $([regex]::escape($matchString))
}
}
Describe "Should -FileContentMatchMultilineExactly" {
It "Case sensitively match all lines" {
$file | Should -FileContentMatchMultilineExactly $([regex]::escape($matchString))
}
}
```
cc @efie45
- If not, use the arrow …

Added FileContentMatchMultilineExactly should assertion

---

src/Main.ps1

Adds support for a `$SCRIPT:additionalPlugins` to be defined to allow outside modules to contribute their own plugins via this method:
```powershell
& (gmo pester) {$f = New-PluginObject etc..; $SCRIPT:additionalPlugins = @($f)
```
See: https://github.com/pester/Pester/discussions/2011#discussioncomment-953966

Enable additional plugins to be added via $additionalPlugins

---

src/Pester.Utility.ps1
src/csharp/Pester/Factory.cs
src/csharp/Pester/Tracing/CodeCoverageTracer.cs
src/functions/Coverage.ps1

Make tracer based CC case insensitive for file paths, because PowerShell will report the path the way it is given, including any casing differences when you invoke the script using . or &.
Fix #2041

Add more logging to BP CC and fix case sensitive new CC

---

src/functions/TestResults.ps1
tst/Pester.RSpec.Nunit.TestResults.ts.ps1

Fixes [https://github.com/pester/Pester/issues/2033](https://github.com/pester/Pester/issues/2033)
_Pester configuration 'TestResult.TestSuiteName' sets name in element 'test-results' instead of name in first element 'test-suite'_

Set name in xml element testsuite

---

src/functions/New-MockObject.ps1
tst/functions/New-MockObject.Tests.ps1

When creating the mock method table for the first time, @{} was assigned into $mockState but on second method NoteProperty would be in $mockState. This lead to only one method being possible to mock, the second mock would throw, because we are indexing into NoteProperty directly, instead of into .Value on NoteProperty.
Fix #2067

Fix mock object with 2 and more methods

---

src/functions/Describe.ps1

Part of a variable name was left by accident in `Invoke-Interactively` when implementing support for parameters with interactive execution in #1787. This causes a slow recursive file search for "Path". 
Related https://github.com/pester/Pester/issues/2076#issuecomment-914688702

Fix slow interactive execution

---

src/Main.ps1
src/Pester.RSpec.ps1
src/Pester.Utility.ps1
src/csharp/Pester/CodeCoverageConfiguration.cs
src/csharp/Pester/FilterConfiguration.cs
src/functions/InModuleScope.ps1
src/functions/New-MockObject.ps1
src/functions/Set-ItResult.ps1
src/functions/SetupTeardown.ps1

This corrects several typos in Pester's documentation, along with some typos in the code comments.
There is a minor typo-related bug corrected by a commit in this PR too, although I do not think it is significant at all. Given how trivial it is, I did not include a test case for it.

Fixes for various typos in Pester documentation and code

---

src/functions/Coverage.ps1
tst/CoverageTestFile.ps1

Fix profiler code coverage in all loops, by making Loop ast the exclusion, instead of naming out the loop types specifically.

Fix Profiler code coverage in all loops

---

src/functions/Mock.ps1

When `Debug.WriteDebugMessages` is enabled, providing a parameter filter to `Should -Invoke` referencing an existing variable multiple times will cause a dict key already exist exception. This PR adds a check to avoid adding the same conflicting variable twice.
Fix #2123 

Fix duplicate key exception in Should-InvokeInternal debug logging

---

src/functions/Context.ps1

fixes vscode-powershell format issue
Fix : #2110 
Fix 'ForEach' parameter casing on Context function. Wrong casing causes vscode-powershell formatter to flip between casings each time you format the PowerShell file

fix ForEach casing in Context

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Updating devcontainer to use latest LTS-versions for NET SDK (6.0) and PowerShell (7.2).
Using Ubuntu 20.04 (focal) to be fully supported for PowerShell and match Azure DevOps-images.

Update devcontainer to NET 6.0 SDK and Powershell 7.2

---

src/functions/New-MockObject.ps1
tst/functions/New-MockObject.Tests.ps1

Fix #2158 
Adds `DefaultParameterSetName` value to `New-MockObject` for backwards compatibility for versions before `5.3.0`.

Adds default parameter set to New-MockObject

---

src/functions/Output.ps1

When container fails, the parameters were not splatted correctly which ends up failing when there are more than 1 errors.
When we capture an error that has not stack trace, like when Import-Module is called directly in the body of test, for module that is missing, we would append new line to the resulting error. This will fail the mandatory parameter validation for Format CI message, and throw. 
I removed appending the new line, and relaxed the parameter rule, because I don't think writing the error should fail when it has a format that is little bit unexpected.

Fix container failure output

---

src/functions/assertions/Should.ps1

Adds Should-example for exception assertion made by @robhalevt to source.
Was added directly to docs-repo were it would be lost during the next build of command reference-docs.
Fix pester/docs#181

Add Should-example for exception-assertion

---

azure-pipelines.yml

Add path exclusions for docs and supportfiles in azure pipeline to avoid unnecessary CI runs. 

Exclude docs and support files from triggering CI

---

src/functions/Pester.SafeCommands.ps1

Fix #2181
Pester will try to run `Get-CimInstance` when `Invoke-Pester` is run with `-OutputFile`. This fails on Nanoserver images with `Microsoft.Management.Infrastructure.CimException: FAILED`. This PR essentially removes `Get-CimInstance` from the list of `SafeCommands` if a Nanoserver installation is detected.

Don't run Get-CimInstance on Nanoserver

---

src/Main.ps1
tst/Pester.RSpec.InNewProcess.ts.ps1

Extends interactive execution to also being triggered from root-level `BeforeDiscovery`.
This is necessary to avoid leaking variables from a `BeforeDiscovery`-block to Run-phase during interactive execution when `BeforeDiscovery` is placed before `Context\Describe` which it usually is. The variables would've been made available in Run-phase from a parent scope.
`Before-/AfterEach` throw when used in root and `Before-/AfterAll` only works when in Discovery-phase, so they're not affected.
Fix #2092

Start interactive execution from BeforeDiscovery

---

src/functions/Coverage.ps1

Code cleanup.
Replace use of alias and positional parameters in Coverage.ps1.

Replace alias and positional parameter usage in Coverage.ps1

---

src/functions/Context.ps1
src/functions/Describe.ps1
tst/Pester.RSpec.InNewProcess.ts.ps1

Stops execution of directly invoked testfile after interactive execution of Pester (triggered by first `Describe`, `Context` or `BeforeDiscovery`) is complete. Will reduce remaining risk of root-level code "corrupting" session [discussed here](https://github.com/pester/Pester/issues/2092#issuecomment-1184956209) to only be code before any of the three blocks mentioned above.
**Current behavior** checks that the same file wasn't just executed to avoid triggering Pester multiple times when the testfile has multiple root-level blocks.
**New behavior** exits the testfile-script using `exit` to cover logic above while also avoiding rerunning any root-level code after the first block that triggered interactive execution. Simplifies the logic in general.
This PR also removes non-invoked check in …

Exit invoked testfile after interactive execution

---

tst/functions/assertions/HaveParameter.Tests.ps1

Param-blocks are no longer required for testcases in `It` in v5.
Removing in `HaveParameter.Tests.ps1` for now but if merged then cleanup should be done in remaining tests as well.

Remove v4 param-blocks from HaveParameter tests

---

src/csharp/Pester/Pester.csproj

In the netstandard2.0 version of Pester.dll there is a requirement for `System.Management.Automation` 6.1.0 or later which blocks users with PowerShell 6.0.x versions from being able to load Pester. 
As there doesn't seem to be a obvious reason for 6.1.0+, this PR downgrades the package reference to the lowest available version on nuget, 6.0.4.
Fix #2207

Fix support for PowerShell 6.0.4

---

src/functions/Environment.ps1
src/functions/TestRegistry.ps1

When `HKCU:\Software\Pester` exists but the user doesn't have permissions, `Test-Path` will currently return true and the user get stuck in a do-until loop while trying to find a unused GUID-subkey during initialization of TestRegistry.
It's now possible to disable TestRegistry (#2008), but since it only hangs the user wouldn't know that TestRegistry was the cause.
Fix #1345

Fix hang in New-TestRegistry when access is denied

---

src/functions/InModuleScope.ps1
src/functions/Mock.ps1
src/functions/Pester.SessionState.Mock.ps1
tst/functions/InModuleScope.Tests.ps1
tst/functions/Mock.Tests.ps1

Adds support for manifest module to `Mock`, `Should -Invoke` and `InModuleScope`.
Fix #1456 
Fix #933 

Support mocking and execution in manifest modules

---

src/csharp/Pester/StringArrayOption.cs
tst/Pester.RSpec.Configuration.ts.ps1
tst/PesterConfiguration.Tests.ps1

Follow-up to #2101 which enabled use of lists when assigning ex. `Run.Path` from hashtable.
This PR enables assigning lists to an existing configuration-object, ex `$c.Run.Path = [arraylist]@()`.
Fix #2100

Add support for assigning lists to StringArrayOption

---

src/Main.ps1

Throws an exception when attempting to add a new operator when there's already 32 registered.
PowerShell only allows 32 parameter sets due to a `uint`-bitmask used to tag which sets a parameter is included in. This won't be fixed in Windows PowerShell and unfortunately PowerShell doesn't throw an exception due to a bug.
When the 33rd (or more) operators are added using `Add-ShouldOperator` it overflows and won't work. The new operator name will use a built-in behavior. Pester currently includes 26 operators, leaving only 6 functional slots for custom assertions per session.
Related #1355
_Issue won't be fixed until operators are used without `Should` parameter sets._
- If not, use the arrow next to `Create Pull Request` to mark it as a draft. PR can be marked `Ready for review` when it's …

Throw in Add-ShouldOperator when max number of operators is reached

---

src/functions/Pester.SessionState.Mock.ps1
tst/functions/Mock.Tests.ps1

Throw in `Should -Invoke` when ex. `-Scope Describe` is used while not inside any `Describe`-blocks.
Adds regression tests for above scenarios, `-Scope It` while not in `It` and `-Scope <negative>`.
Fix #2187

Validate Should -Invoke is invoked in specified -Scope blocktype

---

src/functions/Mock.ps1
src/functions/Pester.SessionState.Mock.ps1
tst/functions/Mock.Tests.ps1

Adds support for `-Because` in `-Invoke` and `-InvokeVerifiable` to be able to customize generic mock assert errors.
`Should -Invoke` already included the parameter, but the internal method didn't support it and threw a `ParameterBindingException`.
Fix #2121
Fix #2228

Add -Because to Should -Invoke and -InvokeVerifiable

---

tst/Format.Tests.ps1
tst/Pester.Tests.ps1
tst/TypeClass.Tests.ps1
tst/functions/Describe.Tests.ps1
tst/functions/Mock.Tests.ps1
tst/functions/Output.Tests.ps1
tst/functions/assertions/BeTrueOrFalse.Tests.ps1
tst/functions/assertions/PesterThrow.Tests.ps1

Removes the remaining param-blocks used for testcase-arguments in our tests as they're no longer needed in v5.
Related #2224 

Cleanup remaining testcase param-blocks in tests

---

src/csharp/Pester/DictionaryExtensions.cs
tst/Pester.RSpec.Configuration.ts.ps1

`GetArrayOrNull()` throws a NRE when value is null, ex. when `Run.Path` was set to `$null` in a hashtable. Added null-check to return before any use of `.GetType()` etc.
Fixing this hashtable-scenario because Pester ignores null-values while casting from hashtable and the error didn't make it clear which option had the problem:
```
InvalidArgument: Cannot convert value "System.Collections.Hashtable" to type "PesterConfiguration". Error: "Object reference not set to an instance of an object."
```
Fix #2026

Fix NRE when assigning null to arrayoption in hashtable

---

src/Pester.Runtime.ps1

For some reason `Install-Module` for Pester 5.1.0+ fails on PowerShell 3 and 4 while testing the module manifest due to an error in a function that's never executed. Not worth figuring out why it's invoked, but fixing the invalid reference to the `$SafeCommands`-dictionary seems to fix it.
Fix #1791

Fix module installation in PowerShell 3 and 4

---

src/functions/assertions/Should.ps1

Fixes a broken link in `Should` help for the custom assertions page at https://pester.dev/docs/assertions.

Fix broken assertions link in help

---

src/csharp/Pester/Pester.csproj
src/csharp/PesterTests/PesterTests.csproj

Use latest C# language version so we can use the latest language features in our code. We ship the code compiled instead of compiling it via Add-Type, so we can safely use whatever version of C# we want.

Use latest C# language version

---

src/functions/assertions/HaveParameter.ps1
tst/functions/Add-ShouldOperator.ts.ps1
tst/functions/assertions/HaveParameter.Tests.ps1

Add support for multiple mandatory aliases for `-HaveParameter`. `-Alias` parameter was changed from a `String` to a `String[]`.
Allows for `Should -HaveParameter Parameter -Alias Alias1, Alias2` to test if parameter `Parameter` has both the aliases `alias1` and `Alias2`. If either one is missing the assert fails.
Fix #2152

Add support for multiple aliases (-Alias) to Should -HaveParameter

---

azure-pipelines.yml

macOS 10.15 image is deprecated in Azure Pipelines. Updating test matrix to use macOS 11 + 12 (latest)
> Deprecation will begin on 5/31/2022 and the image will be fully unsupported by 12/1/22
https://github.com/actions/runner-images/issues/5583

Bump macOS 10.15 to 12 in CI test stage

---

src/Pester.Runtime.ps1
tst/Pester.RSpec.ts.ps1

Update `ExpandedPath` prior to executing a block or test. This will help identify a block or test that was either skipped or failed during setup as parent blocks will be expanded in the path..
Fix #2220

Update ExpandedPath before executing tests and blocks

---

tst/Pester.RSpec.InNewProcess.ts.ps1
tst/Pester.RSpec.Output.ts.ps1

`Invoke-InNewProcress` helper-method in P-tests is broken in PowerShell 7.3 because 7.3 now keeps the backslash previously used to escape quotes in the provided scriptblock.
Replacing with encodedCommand (base64) to avoid version-specific logic.
Fixes broken CI mentioned in https://github.com/pester/Pester/issues/2264#issuecomment-1316554951 . Some runs use prerelease CI-images with PowerShell 7.3 which makes CI inconsistent atm.

Use encodedCommand in Invoke-InNewProcress for P-tests

---

src/functions/assertions/HaveParameter.ps1
tst/functions/assertions/HaveParameter.Tests.ps1

PowerShell doesn't resolve local functions properly for `AliasInfo` when function is defined in local scope in different session state. This affects use of `-HaveParameter` on a mocked command, ex. `Get-Command Should -HaveParameter mockedCommand`
Replace generic NRE with exception that suggests a workaround as this problem is unlikely to be fixed soon in PowerShell and probably not at all in Windows PowerShell.
Fix #1431

Improve error when -HaveParameter is used with mock or alias for local function

---

src/Pester.Runtime.ps1
src/Pester.Utility.ps1
tst/Pester.RSpec.ts.ps1

Create own copy of `Data` per container to avoid ex. default values for script parameters leaking to the next container. Only does a shallow copy to protect the Data-dictionary.
Uses hashtable merging instead of `.Clone()` to simultaneously add support for more dictionary-types. Some dictionaries don't have `ContainsKey()` which results in an exception when adding default values for script parameters to `Data`.
Fix #2299
Fix #2073
Fix #2301 
Fix #2093

Fix script parameter leaking to another container with same Data

---

src/functions/assertions/HaveParameter.ps1
tst/functions/assertions/HaveParameter.Tests.ps1

Get-ParameterInfo wasn't leveraging ASTs because of previous support for PowerShell v2 and required that the opening parenthesis for the param block be on the same line as the keyword.  This change leverages ASTs for Get-ParameterInfo so that HaveParmeter is format agnostic.
Fix #2285

HaveParameter is not dependent on format of param block

---

src/functions/assertions/BeOfType.ps1
src/functions/assertions/HaveParameter.ps1
tst/functions/assertions/BeOfType.Tests.ps1
tst/functions/assertions/HaveParameter.Tests.ps1

Include expected type in exceptions when type is not resolvable

---

src/functions/Mock.ps1

There is initial cleanup of orphaned mocks that happens in Invoke-Pester and makes sure that there are no Mock aliases in place coming from previously cancelled runs. In Pester v4 we only cleaned up the main session state, but in v5 we pick up every loaded module and clean up there. This adds up to the point where it can take several seconds (in docker container) to do this cleanup. 
This PR optimizes the cleanup to just query functions, rather than all cmdlets and filtering them.

Make initial Mock cleanup more performant

---

src/functions/assertions/BeNullOrEmpty.ps1
tst/functions/assertions/BeNullOrEmpty.Tests.ps1

Fix missing quotes when single string is passed to `Should -BeNullOrEmpty`.
/cc @johlju 

Quote input string in BeNullOrEmpty error

---

src/functions/Mock.ps1
tst/functions/Mock.Tests.ps1

Fixing edge case where creating a mock with both `-RemoveParameterType` and `-RemoveParameterValidation` for the same parameter would not work properly if `[PSTypeName('asd')]` was defined below validation-attribute

Remove parameter attributes in reverse in Mock

---

src/Main.ps1
src/Pester.RSpec.ps1
src/csharp/Pester/OutputConfiguration.cs
src/functions/Output.ps1
tst/Pester.RSpec.Configuration.ts.ps1
tst/functions/Output.Tests.ps1

Added parameter 'CITreatErrorsAsWarnings' to output configuration. When true, errors will be logged in CI as warnings.
Fix #2295

CI Treat Errors As Warnings - ref #2295

---

src/Main.ps1
src/functions/Pester.SessionState.Mock.ps1
tst/functions/Mock.Tests.ps1

Ignores mock cleanup on start when in a nested Invoke-Pester run.
Fix #2074

Do not cleanup previous mocks in inner Invoke-Pester

---

build.ps1

Adds a `-Configuration` parameter to build.ps1 to allow building assembly in debug-configuration. Defaults to Release like before.
Release mode requires using `justmycode: false` option when debugging assembly with VSCode, which requires more complicated launch-config.
Also adds some AI-generated (🪄🤖)  help and minor formatting-changes.

Support building assembly with Debug configuration

---

src/functions/assertions/HaveParameter.ps1
tst/functions/assertions/HaveParameter.Tests.ps1

Adds support for asserting parameter in a specific parameter set.
This only affects whether parameter exists (or not) and if exists in set and mandatory.
Fix #2227

Add -InParameterSet in Should -HaveParameter

---

src/Pester.Utility.ps1
src/functions/assertions/Should.ps1
tst/functions/assertions/Should.Tests.ps1

**Possible breaking change!**
If an enumerable was provided with `Should -ActualValue ..` instead of pipeline, unroll to be consistent with pipeline-input.
Fix #2314
Might also solve this: https://github.com/pester/Pester/issues/1234#issuecomment-748627991

Avoid nested array when using Should -ActualValue

---

src/Main.ps1
src/functions/Environment.ps1
src/functions/TestDrive.ps1
src/functions/TestRegistry.ps1
tst/functions/TestDrive.Tests.ps1
tst/functions/TestRegistry.Tests.ps1

When running Pester inside Pester, it would delete the existing/parent TestDrive/TestRegistry.
This PR detects, stores and reattaches the previous TestDrive/TestRegistry drives before returning to the parent instance.
Also remaps TestDrive/TestRegistry at end of block if missing. This can occur if user code removes it or a inner/nester Invoke-Pester failed and never got to reattach it.
Fix #2147

Reattach TestDrive and TestRegistry after running inner Invoke-Pester

---

src/csharp/Pester/RunConfiguration.cs

Improve wording for Exit option.
Fix #2338

Add Run.Exit option clarification

---

src/Main.ps1
src/Pester.Runtime.ps1
src/functions/Context.ps1
src/functions/Describe.ps1
tst/Pester.RSpec.ts.ps1

Add default values for unused script parameters to container's Data before executing `BeforeDiscovery`. Avoids changes to the variables in `BeforeDiscover` from being captured and sent to Run-phase.
**Known limitation:** Changing the variable outside `BeforeDiscovery/Describe/Context` would still modify it in Data. Can't fix as we don't have a hook to execute code before it. Root-level code is also discouraged in Pester v5.
Fix #2359

Add missing container-parameters to Data before BeforeDiscovery

---

tst/PTestHelpers.psm1
tst/Pester.RSpec.InNewProcess.ts.ps1
tst/Pester.RSpec.Output.ts.ps1

After switching to `-EncodedCommand` for child `powershell/pwsh` processes in P-tests (#2267) we get CliXML-output in CI logs and false errors in CI-report.
Using `-EncodedCommand` changes default output to XML in non-interactive environments with redirected output like our AzDO Pipelines CI. The normal workaround of explicitly setting `-OutputFormat Text` is not honored prior to PS 6.2 (incl. 5.1). 
This PR reverts to using `-Command` with different commands to handle the changed argument-behavior in PS 7.3+. It also extracts the helper to a `PTestHelpers` module to reduce duplicated code.
Fix #2340 

Fix false errors and broken CI-logs from P-tests

---

.github/workflows/code-analysis.yml

The PSSA workflow shows a warning about node 12 being deprecated. Bumping checkout-action to v3 which runs on node 16.

Upgrade to action/checkout v3 in PSSA workflow

---

src/functions/Output.ps1

Fixes trailing ANSI reset sequence in pipeline run summary for errors etc. by using `ConsoleColor` RenderMode instead of `Ansi` when printing errors with AzureDevOps CI-format.
Fix #2350

Fix ANSI sequence shown in Azure DevOps summary

---

src/functions/assertions/HaveParameter.ps1
tst/functions/assertions/HaveParameter.Tests.ps1

This PR enhances `Should -HaveParameter` assertion with:
- Throws exception when `-DefaultValue` is used with unsupported command types like binary cmdlet
- Throws exception when `ApplicationInfo`-object is used as input value to `Should -HaveParameter`
- Adds support for using `-DefaultValue` when provided resolvable `AliasInfo`.
- Adds support for using `-DefaultValue` with script parameters (https://github.com/pester/Pester/pull/2288#discussion_r1111312637)
Fix #2286
Fix #2290

Support Should -HaveParameter -DefaultValue for AliasInfo and scripts

---

src/functions/assertions/PesterThrow.ps1
tst/functions/assertions/PesterThrow.Tests.ps1

Enhances `Should -Throw` assertion with:
- Improved filter-summary in error message
- Specifically using word `like` for message-filter to hint at the use of `-like` operator.
Related discussion https://github.com/pester/Pester/issues/1793
- Removes duplicate helper-functions covered by `Format.ps1`
- Fixes error when ActualValue is missing or not a scriptblock.
**Missing BEFORE**
**Non-scriptblock BEFORE** (conversion error = printed whole function)
**Missing or Non-scriptblock AFTER**
Fix #2064

Update error messages in Should -Throw

---

src/Main.ps1
src/Pester.Runtime.ps1
tst/Pester.RSpec.ts.ps1

Always create new Container-objects during runtime to avoid mutating reusable input/configuration.
Fix #2357

Fix parameter default values leaking to Data in user-provided Container

---

src/functions/Context.ps1
src/functions/Describe.ps1
src/functions/It.ps1

Renames `-TestCases` parameter on `It` to `-ForEach` to follow documentation, and be consistent with Describe and Context. 
Fixes the docs in inline help to use that name. 
The former `-TestCases` name is made an alias.
$testCases in the examples is kept on purpose to make it easy to see what is being referred as array of hashtables. 
Fix #2310

Rename TestCases parameter to ForEach

---

src/Pester.Runtime.ps1
src/functions/Output.ps1
src/functions/Set-ItResult.ps1
tst/functions/Set-ItResult.Tests.ps1

- Set-ItResult updated to return distinctive ErrorId depending on switch used (previously always returned `PesterTestSkipped`).
- `-Inconclusive` now returns `PesterTestInconclusive`
- `-Pending` now returns `PesterTestPending`
- `Skipped` still returns `PesterTestSkipped`
- Invoke-TestItem in Pester.Runtime updated to handle additional ErrorId´s.
- Existing Set-ItResult Pester tests re-enabled.
I am not sure if these changes require additional tests and/or documentation updates - let me know if they do.
Related to issue #2400.

Set-ItResult: Return distinctive ErrorId depending on switch used

---

src/functions/assertions/HaveParameter.ps1
tst/functions/assertions/HaveParameter.Tests.ps1

Fix Should -HaveParamter -DefaultValue

---

.github/workflows/code-analysis.yml

Code analysis workflow running PSScriptAnalyzer reports warnings due to node16 being deprecated. PR updates actions used in workflow to version running node20.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Update code-analysis workflow to node20 actions

---

src/Main.ps1
src/Pester.RSpec.ps1
src/Pester.Runtime.ps1
src/csharp/Pester/Container.cs
src/csharp/Pester/Run.cs
src/csharp/Pester/Test.cs
src/csharp/Pester/ToStringConverter.cs
src/en-US/about_Pester.help.txt
src/functions/It.ps1
src/functions/Output.ps1
src/functions/Set-ItResult.ps1
src/functions/TestResults.NUnit25.ps1
src/functions/TestResults.NUnit3.ps1
tst/Pester.RSpec.Output.ts.ps1
tst/Pester.RSpec.ResultObject.ts.ps1
tst/Pester.RSpec.TestResults.NUnit25.ts.ps1
tst/Pester.RSpec.TestResults.NUnit3.ts.ps1

- Adds properties to CSharp classes to enable `Inconclusive` and `InconclusiveCount` properties on the `Pester.Run` object.
- Adds logic to group and count tests marked as inconclusive.
- Pester Report output updated to support Inconclusive counts etc.
- Adds deprecation notice shown when `Set-ItResult -Pending` is used in tests.
- NUnit reports updated to handle inconclusive tests (needs thorough review).
- Minor changes to help text
Fix #2400
I think the logic to handle inconclusive tests is sound, but I am looking for feedback on these points
- Are implemented changes to NUnit reports sufficient, or did I miss anything?
- Does this PR call for new tests or …

Handle tests marked as inconclusive

---

src/functions/Context.ps1
src/functions/Describe.ps1
src/functions/It.ps1

`-Skip` was missing help in `Context` and `Describe` functions. False positive due to commented `-Focus` switch in the parameter-block.

Add missing help for -Skip in Context and Describe

---

src/functions/assertions/FileContentMatchMultiline.ps1
src/functions/assertions/FileContentMatchMultilineExactly.ps1

Adds missing section to operator help message used for https://pester.dev .
Got lost in #2336

Fix docs for FileContentMatchMultiline* operators

---

tst/PTestHelpers.psm1
tst/Pester.RSpec.BackCompat.ts.ps1
tst/Pester.RSpec.Configuration.ts.ps1
tst/Pester.RSpec.Coverage.ts.ps1
tst/Pester.RSpec.Demo.ts.ps1
tst/Pester.RSpec.Pester4ResultObject.ts.ps1
tst/Pester.RSpec.ResultObject.ts.ps1
tst/Pester.RSpec.TestResults.JUnit4.ts.ps1
tst/Pester.RSpec.TestResults.NUnit25.ts.ps1
tst/Pester.RSpec.TestResults.NUnit3.ts.ps1
tst/Pester.RSpec.ts.ps1
tst/Pester.Rspec.Filtering.ts.ps1
tst/Pester.Runtime.ResultObject.ts.ps1
tst/Pester.Runtime.ts.ps1
tst/Pester.Utility.ts.ps1
tst/functions/Add-ShouldOperator.ts.ps1
tst/functions/New-Fixture.ts.ps1
tst/functions/Pester.TestDrive.ts.ps1
tst/functions/Pester.TestRegistry.ts.ps1

Extracts shared helper-functions in P-tests to `PTestHelper`-module, as mentioned in https://github.com/pester/Pester/pull/2345#discussion_r1192973682

Extract common helper-functions in P-tests

---

src/csharp/Pester/Container.cs
src/csharp/Pester/ContainerInfo.cs
src/csharp/Pester/ToStringConverter.cs
src/functions/Output.ps1
src/functions/TestResults.JUnit4.ps1
src/functions/TestResults.NUnit25.ps1
src/functions/TestResults.NUnit3.ps1
src/functions/TestResults.ps1
tst/Pester.RSpec.TestResults.JUnit4.ts.ps1

This PR adds a `Name`-property to Container-objects to standardize naming currently set in multiple places.
There was two variations in the codebase when container type was `File`:
- `$Item.ToString()` which is FullName in PS7, but Name in Windows PowerShell
- `$Item.FullName`
**After PR:** Prefer `FullName` if `FileInfo`-object for consistency, else `ToString()`.
There was two variations in the codebase when the scriptblock was linked to a file:
- `<ScriptBlock>file:line`
- `<ScriptBlock>:file:line`
**After PR:** `<ScriptBlock>:file:line`
PR also moves container type validation to property setter to avoid checking in multiple places.

Standardize container name and type validation

---

tst/p.psm1

Tests with special characters in name would fail during filter-evaluation.
Example pre-PR:
```powershell
. '/workspaces/Pester/tst/Pester.RSpec.TestResults.NUnit3.ts.ps1'
| - Write NUnit3 test results 
WildcardPatternException: The specified wildcard character pattern is not valid: *handles special characters well -!@#$%^&*()_+1234567890[];',./"-
```

Fix WildcardPatternException when using dt in P

---

src/functions/TestResults.NUnit3.ps1
tst/Pester.RSpec.TestResults.NUnit3.ts.ps1

Handles null-objects when exporting `StandardOutput` to NUnit3 output-element.
Fix #2421

Fix possible NRE in NUnit3 export

---

publish/release.ps1
src/Pester.Runtime.ps1
tst/Pester.Runtime.ts.ps1

Mark blocks (incl. container root) as Skip when no child tests will run. This is done to avoid running `BeforeAll/AfterAll` when it's not needed.
Fix #2439
Fix #2449

Skip blocks without runnable tests

---

src/Pester.RSpec.ps1
src/Pester.Utility.ps1
src/functions/Get-SkipRemainingOnFailurePlugin.ps1
tst/Pester.RSpec.ts.ps1

- Refactors plugin to reduce code duplication.
- Ignores tests excluded by filters or explicitly skipped using `-Skip` from being marked as skipped by `Run.SkipRemainingOnFailure` option.
- Marks relevant blocks as skipped to avoid running `BeforeAll/AfterAll`
Fix #2440
Fix #2424

Ignore excluded/skipped tests and unnecessary setup/teardown using SkipRemainingOnFailure

---

src/Main.ps1

Result object was printed when run failed because it was sent to standard output, but never reached variable assignment before `Run.Exit` killed the process causing a text dump.
Fix #2300 

Ignore PassThru when run fail while using Run.Exit

---

publish/release.ps1
src/Main.ps1

Hides parameters only used by legacy compatibility-set in `Invoke-Pester` from tab-completion, intellisense etc.
> [!NOTE]
> `DontShow` can't be used with parameters used in multiple sets. It will always hide the parameter regardless of previous parameters in the command.
Fix #1586

Hide legacy-only parameters in Invoke-Pester

---

publish/release.ps1
src/functions/assertions/Should.ps1
tst/Pester.RSpec.ts.ps1

Removes the custom exception thrown when calling `Should` with legacy Pester 3 syntax. The syntax is not supported and the custom error caused too many false positives.
Before:
```powershell
> 1 | Should Be 2
Should: Cannot retrieve the dynamic parameters for the cmdlet. Legacy Should syntax (without dashes) is not supported in Pester 5. Please refer to migration guide at: https://pester.dev/docs/migrations/v3-to-v4
```
After:
```powershell
> 1 | Should Be 2                               
Should: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```
Fix #2437
Fix #2138
> [!NOTE]
> If rollback becomes necessary, include code in #2325 to fix #2138
- If not, use …

Remove Should legacy syntax error

---

src/Pester.RSpec.ps1
src/csharp/Pester/CodeCoverageConfiguration.cs
src/functions/Coverage.ps1
tst/functions/Coverage.Tests.ps1

Remove experimental flag from Profiler based Code Coverage and use it by default because it is way more performant.
 
Fix https://github.com/pester/Pester/issues/2441

Set profiler based CodeCoverage as default

---

tst/functions/assertions/PesterThrow.Tests.ps1

This has been bugging me for a while 😄 

Remove blank output in PesterThrow.Tests.ps1

---

tst/functions/New-Fixture.ts.ps1

This happens really early in test.ps1, and it always scares me that tests are failing.

Hide failing output that always scares me

---

src/functions/Output.ps1

Added null check for `$host.UI` and `$host.UI.properties` to avoid race condition in PowerShell when accessing the properties from multiple threads.
Fixes #2383.

Add null check for $host.UI and its properties to avoid race condition (#2383)

---

Pester.BuildAnalyzerRules/Pester.BuildAnalyzerRules.psm1
build.ps1
src/Main.ps1
src/Pester.State.ps1
src/csharp/Pester/Factory.cs
src/functions/Get-ShouldOperator.ps1
src/functions/Mock.ps1
src/functions/TestResults.ps1
src/functions/assertions/Should.ps1

Replaces `$SafeCommands['New-Object']` calls with `::new()` for improved readability and minor perf. Also removes a helper method in `Pester.Factory` that's no longer needed.
Leaving similar change in tests for a future PR to make sure any failures are actually code's fault.

Replace New-Object calls with ::new()

---

src/functions/Mock.ps1

Fixes NRE using mock debug logging when `Should-Invoke` with `-ParameterFilter` is used for a mocked native application. Caused by variable conflict-logging looking for CommandMetaData which doesn't exist for external commands = N/A logging.
Fix #2479 
Backport to 5.6.0

Fix NRE in mock debug log for native commands

---

azure-pipelines.yml

MacOS 11 image is deprecated in Azure Pipeline and Github will remove it in [June 2024](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal). Github manages runners for Azure Pipelines so it'll likely be removed soon after.
Bumping to MacOS 12 + 13 as a hotfix while waiting on stable macOS 14 image.

Replace deprecated macOS 11 image with 13 in CI

---

.github/workflows/code-analysis.yml
azure-pipelines.yml
src/csharp/Pester/Pester.csproj
src/csharp/Pester/Tracing/CodeCoverageTracer.cs
src/csharp/Pester/Tracing/ExternalTracerAdapter.cs
src/csharp/Pester/Tracing/ITracer.cs
src/csharp/Pester/Tracing/Tracer.cs
src/csharp/Pester/Tracing/TracerHostUI.cs
src/csharp/Sync-WithProfiler.ps1
src/functions/Coverage.ps1
test.ps1
tst/Pester.Mock.ClassMetadata.ps1
tst/functions/Mock.Tests.ps1

Testing how we could measure CodeCoverage of Pester and P tests.  The code above runs, except for one test in mock, which is strange since we can Profile pester tests. Maybe it was some fluke. 
Fix #2475

Report code coverage that includes P tests

---

src/Module.ps1
src/Pester.psd1
src/en-US/about_Mocking.help.txt
src/functions/Pester.SessionState.Mock.ps1
tst/Help.Tests.ps1
tst/Pester.Mock.ClassMetadata.ps1
tst/functions/Mock.Tests.ps1

Removes Assert-MockCalled and Assert-VerifiableMock legacy wrapper functions. They were deprecated and planned removed in 5.x.

Remove Assert-MockCalled and Assert-VerifiableMock

---

SECURITY.md
SUPPORT.md

Fix security and support

---

src/Pester.RSpec.ps1
src/csharp/Pester/ShouldConfiguration.cs
src/functions/assertions/Should.ps1
tst/Pester.RSpec.Configuration.ts.ps1

Add option to disable Should -Be and other assertions shipped with Pester v5, so when you migrate you don't accidentally regress.
Fix #2495

Add option to disable v5 syntax

---

src/functions/assert/Equivalence/Should-BeEquivalent.ps1
tst/functions/assert/Equivalence/Should-BeEquivalent.Tests.ps1

Removes "Getting default equivalency options" warning spam in `tests.ps1` ouptut. Fixed by providing default options by... well, default in `Should-BeEquivalent.Tests.ps1`.
_Also replaces some calls to `New-Object`_

Fix console warnings in Should-BeEquivalent.Tests.ps1

---

src/functions/assert/String/Should-BeString.ps1
tst/functions/assert/String/Should-BeString.Tests.ps1

Add -TrimWhitespace to Should-BeString

---

src/Module.ps1
src/Pester.psd1
src/functions/assert/Equivalence/Should-BeEquivalent.ps1
tst/functions/assert/Equivalence/Should-BeEquivalent.Options.Tests.ps1

Replace Get-EquivalencyOptions with parameters on Should-BeEquivalent.
Fix #2477

Replace Get-EquivalencyOptions with parameters

---

README.md

Fix #2438
Updated so that there is a notice at top of readme and a list futher down of all certificate issuers, and thumbprint going back to 3.0.3
after installing all available versions from ps module store i ran the following command to list all the different module certificates
``` powershell
get-module pester -ListAvailable|%{$sign = Get-AuthenticodeSignature -FilePath $_.Path;[pscustomobject]@{version=$_.version;issuer=$sign.SignerCertificate.Issuer;thumbprint=$sign.SignerCertificate.Thumbprint;subject=$sign.SignerCertificate.Subject}}|ft -a
```
after that i just manually found the different certificate thumbprint and figured out the certificate for the different certificate ranges.
I noted that 3.4.0 had a different certificate subject due to it being released as a w10 module, but …

Update cert-notice readme

---

src/functions/assert/Equivalence/Should-BeEquivalent.ps1
tst/functions/assert/Equivalence/Should-BeEquivalent.Tests.ps1

Better wording in Should-BeEquivalent
co-authored with: @powershellpr0mpt

Use the actual object instead of 'the other'

---

src/functions/assert/Collection/Should-All.ps1
src/functions/assert/Collection/Should-Any.ps1
tst/functions/assert/Collection/Should-Any.Tests.ps1

Should-Any was not passing when at least one item was passing the predicate, because output is $null when you run with Should-* assertion in the predicate, and it does not fail. But that was converted to $false, and so the item did not pass.

Fix collection assertions with Should

---

src/functions/TestResults.NUnit3.ps1
src/functions/TestResults.ps1
tst/Pester.RSpec.TestResults.NUnit3.ts.ps1

The following test will fail to generate an NUnit report:
```
Describe 'Describe VT Sequences' {
Write-Output "`e[32mHello World`e[0m"
$true | Should -Be $true
}
```
This will fail because WriteCData does not support writting the ESC character, which is a valid [VT sequence](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences).
The fix is to replace the ESC and Bell characters for {ESC} and {BELL}. 
According to the [Xml CDATA spec](https://www.w3.org/TR/REC-xml/#NT-Char), there is no way to escape these characters, other than failing, but we still need to represent them in the NUnit report.
Afte this change, these characters will be represented as by its printable version in the unicode table: `␛` for the `ESC` (0x1B) and as `␇` for the `BELL` (0x07) in …

Fix a bug where the NUnit-Report fails to generate if the test output contains Virtual Terminal Sequences

---

src/Main.ps1
src/Pester.RSpec.ps1
src/Pester.Runtime.ps1
src/functions/New-Fixture.ps1
src/functions/TestResults.ps1

Defines OutputType for functions returning typed objects to enable tab-completion/intellisense while writing code without executing it. Especially useful for `New-PesterConfiguration` when writing quick demos.
**Note:** Tab-completion currently ignores ParameterSet defined in `[OutputType]`, so no need to split them in e.g. `ConvertTo-*UnitReport`

Add OutputType to improve tab-completion/intellisense

---

src/functions/Coverage.ps1
tst/Pester.RSpec.Coverage.ts.ps1

Temporary fix to implement `CodeCoverage.ExcludeTests` until CodeCoverage configuration parsing either implements old advanced interface or removes the old code and updates tests.
Fix #2514

Implement CodeCoverage.ExcludeTests

---

tst/testProjects/CoverageTestFile.Tests.ps1

I'm not sure how #2523 passed checks, but this file was not committed. Discovered in backport PR #2524 where tests failed.

Add missing test file

---

azure-pipelines-publish.yml
publish/release.ps1
publish/signModule.ps1

Add pipeline for signing code on server and change script to use KeyVault tools for signing rather than local certificate.

Sign on server

---

src/csharp/Pester/RunConfiguration.cs
src/en-US/about_PesterConfiguration.help.txt
src/functions/Context.ps1
src/functions/Describe.ps1
src/functions/It.ps1
tst/Format2.Tests.ps1
tst/Pester.RSpec.Configuration.ts.ps1
tst/Pester.RSpec.ts.ps1
tst/functions/assert/Time/Should-BeAfter.Tests.ps1
tst/functions/assert/Time/Should-BeBefore.Tests.ps1

Throw during Discovery when `Describe/Context/It` is provided `$null` or `@()` to `-ForEach/TestCases` to avoid silent failure. 
The previous behavior, ignoring the test/block, can be achieved by setting the configuration option `Run.FailOnNullOrEmptyForEach` to `$false`.
When enabled, individual blocks or tests can be overriden to allow empty array or null by adding a new `-AllowNullOrEmptyForEach` parameter to `Describe/Context/It`, e.g. if a test is generated using external data which might be empty.
Fix #2151 

Throw when providing null or empty array to -ForEach

---

src/functions/assert/Exception/Should-Throw.ps1
tst/functions/assert/Exception/Should-Throw.Tests.ps1

Support same positional arguments in `Should-Throw` as `Should -Throw` in v5.
Fix #2527

Support v5 positional syntax in Should-Throw

---

src/Pester.RSpec.ps1
src/functions/Coverage.ps1
tst/Pester.Tests.ps1

Updates `Find-File` and `Get-CodeCoverageFilePaths` internal functions to exclude duplicate files when provided overlapping `Path` values to search in. This affects:
- Test file paths provided using `-Path / Run.Path`
- Code Coverage source file paths provided using `-CodeCoverage / CodeCoverage.Path`
- Containers created using `New-PesterContainer -Path ..`
- Mulitple containers can still call the same file, e.g. to invoke it with different `Data` (parameters)
PR also:
- Refactors `Get-CodeCoverageFilePaths` to use `Get-ChildItem -File -Recurse` for increased performance.
- Refactors `New-PesterContainer` to avoid multiple filesystem searches when provided array of Data for increased performance.
Fix #2530
- If not, use the arrow next to `Create Pull Request` to mark it as a draft. PR …

Exclude duplicate files for Run.Path and CodeCoverage.Path

---

src/functions/assertions/PesterThrow.ps1
tst/functions/assertions/PesterThrow.Tests.ps1

This target v5. This resolves #2558 so that when the expected message containing escaped wildcard is output is removes the escaped character so it shows the correct expected message that differ from the actual value.
Part of issue #2558 

Fix `Should -Throw` to handle expected message with escaped wildcard (backport)

---

src/functions/assert/Exception/Should-Throw.ps1
src/functions/assertions/PesterThrow.ps1
tst/functions/assert/Exception/Should-Throw.Tests.ps1
tst/functions/assertions/PesterThrow.Tests.ps1

This target v6. This resolves #2558 so that when the expected message containing escaped wildcard is output is removes the escaped character so it shows the correct expected message that differ from the actual value.
Fix #2558 

Fix `Should-Throw`/`Should -Throw` to handle expected message with escaped wildcard

---

src/functions/Coverage.ps1
tst/functions/Coverage.Tests.ps1

Calls to base constructors like `base()` were discovered never hit by breakpoint or tracer CC. PowerShell only hits scriptblock contents of both constructors.
Adding base ctor call to ignore command list.
Issue reported on Discord: https://discord.com/channels/180528040881815552/447476910499299358/1268943815272828998

Ignore call base class contructor in code coverage

---

src/functions/assert/Collection/Should-BeCollection.ps1
tst/functions/assert/Collection/Should-BeCollection.Tests.ps1

Add `-Count` to Should-BeCollection with the usual caveat of not being able to tell single item array from single item when using `|` syntax.
Fix #2534

Add -Count to Should-BeCollection

---

src/Main.ps1
src/Pester.Runtime.ps1
src/functions/Context.ps1
src/functions/Describe.ps1
src/functions/It.ps1
src/functions/SetupTeardown.ps1
src/functions/assert/Collection/Should-All.ps1
src/functions/assert/Collection/Should-Any.ps1
src/functions/assert/Exception/Should-Throw.ps1
tst/Pester.RSpec.ts.ps1
tst/functions/Add-ShouldOperator.ts.ps1
tst/functions/Context.Tests.ps1
tst/functions/Describe.Tests.ps1
tst/functions/It.Tests.ps1
tst/functions/Mock.Tests.ps1
tst/functions/SetupTeardown.Tests.ps1
tst/functions/assert/Collection/Should-All.Tests.ps1
tst/functions/assert/Collection/Should-Any.Tests.ps1
tst/functions/assert/Exception/Should-Throw.Tests.ps1

Throws when user provides scriptblocks that are not bound to a session state. They would be executed in Pester's module state which could cause unexpected behaviour.
Examples:
Fix #2411
Checklist:
- Not applicable as it always overrides session state to specified module
- Already handles unbound scriptblocks. Test added
- Already handles unbound scriptblocks. Test added

Throw on unbound user-provided scriptblocks

---

azure-pipelines.yml

- Replaces deprecated macOS 12 runner image with macOS 14,
- Upgrades PublishCodeCoverageResults to v2 because v1 is deprecated. See warnings in recent CI runs.

Update macOS image and PublishCodeCoverageResults task in CI

---

src/Pester.RSpec.ps1

Removes about_PesterConfiguration from related links in `New-PesterConfiguration` as it generates broken (empty) markdown links in platyPS. about_pesterConfiguration is already mentioned in Description-section.
Related https://github.com/pester/docs/pull/329#discussion_r1845457577

Remove about topics in related links

---

build.ps1
publish/filesToPublish.ps1
src/csharp/Pester/CodeCoverageConfiguration.cs
src/en-US/about_PesterConfiguration.help.txt
src/functions/Coverage.Plugin.ps1
src/functions/Coverage.ps1
src/schemas/Cobertura/coverage-loose.dtd
tst/functions/Coverage.Tests.ps1

Backport #2298 to 5.x.x
Backport #2553 as well

[rel/5.x.x] Implement Cobertura coverage format

---

tst/functions/Coverage.Tests.ps1

Forward porting a fix for powershell pre-v5, that I had to do here https://github.com/pester/Pester/pull/2572
We don't run that code on the main branch, but we might be backporting more fixes of code coverage back to v5, and this makes it easier.

Fix coverage code for pre-v5

---

src/Main.ps1
src/Pester.RSpec.ps1
src/functions/Context.ps1
src/functions/Describe.ps1
src/functions/Get-ShouldOperator.ps1
src/functions/InModuleScope.ps1
src/functions/It.ps1
src/functions/New-Fixture.ps1
src/functions/New-MockObject.ps1
src/functions/Pester.SessionState.Mock.ps1
src/functions/Set-ItResult.ps1
src/functions/SetupTeardown.ps1
src/functions/TestResults.ps1
src/functions/assertions/Should.ps1
tst/Help.Tests.ps1

Updates website links to use versioned URLs to make sure they don't break when v6 is released.
Fix #2503

Use versioned links for online v5 docs

---

src/functions/Coverage.ps1
src/functions/TestResults.NUnit25.ps1
src/functions/TestResults.NUnit3.ps1
tst/functions/Coverage.Tests.ps1

Extends code coverage to include `break`, `continue`, `exit` and `throw` statements.
`return` is not included due to inconsistent behavior (though `return 123` is already covered as a command expression)
Adds sort after `Group-Object` to save future headaches with inconsistent report/output order in Windows PowerShell vs PowerShell 6.1 which sorts by default.
Fix #1465

Include more statements in code coverage

---

src/functions/assert/Equivalence/Should-BeEquivalent.ps1
src/functions/assert/General/Should-NotBeSame.ps1
src/functions/assert/String/Should-BeLikeString.ps1
src/functions/assert/String/Should-NotBeEmptyString.ps1
src/functions/assert/String/Should-NotBeString.ps1
src/functions/assert/Time/Should-BeAfter.ps1
src/functions/assert/Time/Should-BeBefore.ps1
src/functions/assert/Time/Should-BeFasterThan.ps1
src/functions/assert/Time/Should-BeSlowerThan.ps1

Adds missing linebreaks between code and description in examples.

Cleanup examples for v6 assertions

---

src/functions/Set-ItResult.ps1
tst/functions/Set-ItResult.Tests.ps1

Fix #2588
Fixes the formatting of the `Set-ItResult` exception message when a `-Because` is provided.
This change removes the "because" being added to the message before including the content of `Format-Because` (which includes the "because"). It also strips out the trailing comma, as it's not needed or expected here.
The current message is formatted with a redundant "because" and a trailing comma.
ex:
```powershell
try {
Set-ItResult -Skipped -Because "we are forcing it to skip"
} catch {
$_.Exception.Message
}
```
Expected:
```powershell
is skipped, because we are forcing it to skip
```
Actual:
```powershell
is skipped, because  because we are forcing it to skip,
```
- If not, use the arrow next to `Create Pull Request` to mark it as a draft. PR can be marked `Ready for review` when …

Fix formatting for Set-ItResult with because, removing trailing comma and redundant "because"

---

src/csharp/Pester/CoverageLocationVisitor.cs
src/functions/Coverage.ps1
tst/functions/Coverage.Tests.ps1

Fixes #2268
This PR adds support for excluding specific code constructs from coverage analysis using `[ExcludeFromCodeCoverageAttribute()]`.
- New CoverageLocationVisitor: Skips AST nodes in script blocks marked with [ExcludeFromCodeCoverageAttribute()].
- Get-CommandsInFile updated: Replaced predicate-based filtering with CoverageLocationVisitor.
- Updated Tests: Ensures nodes with [ExcludeFromCodeCoverageAttribute()] are skipped.
Verifies inclusion of unmarked nodes and relevant control flow statements.

Add support for excluding functions from coverage with attribute

---

src/functions/Mock.ps1
tst/functions/Mock.Tests.ps1

Fix #1274
This pull request resolves the issue where mocked functions fail to handle dynamic parameters with conflicting names (e.g., `PSEdition`).
- Added `Repair-ConflictingDynamicParameters` to rename conflicting parameters (e.g., `_PSEdition`) and add aliases for the original names.
- Updated `Get-MockDynamicParameter` to resolve conflicts for Cmdlet and Function parameter sets.
- Updated `Get-ContextToDefine` to new logic.
- Added tests from the linked issue to validate renamed and aliased dynamic parameters. Minor modifications to the tests:
- replaced `Assert-MockCalled` with `Should -Invoke`
- replaced `$PSEdition` with `$_PSEdition` in the ParameterFilter
- If not, use the arrow next to `Create Pull Request` to mark it as a draft. PR can be marked `Ready for review` when it's …

Fix handling of conflicting dynamic parameters

---

src/functions/assertions/BeOfType.ps1
tst/PesterConfiguration.Tests.ps1
tst/functions/Get-ShouldOperator.Tests.ps1
tst/functions/New-MockObject.Tests.ps1
tst/functions/TestsRunningInCleanRunspace.Tests.ps1

Adds an example to `-BeOfType` using `TypeInfo` as input. Types has to be wrapped with parantheses to avoid PowerShell from making it a string argument which might not resolve for PowerShell classes and internal types.
Fix #2414

Update help and tests to use parantheses around type input in BeOfType assertions

---

src/functions/New-MockObject.ps1
tst/functions/New-MockObject.Tests.ps1

Updates `New-MockObject` with examples for using type objects to reference classes.
Fix #2564

Update New-MockObject examples to use type object as input

---

src/Pester.RSpec.ps1

about_* links as `.LINK` sections in comment based help breaks the docs website build. PR removes the last one from `New-PesterConfiguration` which was already removed in v6/main.

v5: Remove about_PesterConfiguration link in New-PesterConfiguration

---

src/functions/TestResults.NUnit3.ps1

VT sequences are invalid in CData.
If an error message contains a VT sequence (for example to change the console color to red), then the NUnit report will fail to save.

Pester may fail to produce report if an error message contains VT sequences

---

src/csharp/Pester/DebugConfiguration.cs
src/en-US/about_PesterConfiguration.help.txt
src/functions/Output.ps1
tst/Pester.RSpec.Configuration.ts.ps1
tst/Pester.RSpec.Output.ts.ps1

Allow displaying an indication when each test starts:
```
[|] Test name...
```
(Parity with ShowNavigationMarkers)
fixes #2583

Add configuration.Debug.ShowStartMarkers support

---

azure-pipelines.yml

Ubuntu 20.04 runner image is deprecated in April, see https://github.com/actions/runner-images/issues/11101. Updating CI to use 22.04 and 24.04

Update Ubuntu images in CI

---

src/Module.ps1
src/Pester.psd1
src/functions/assert/Parameter/Should-HaveParameter.ps1
src/functions/assert/Parameter/Should-NotHaveParameter.ps1
tst/functions/assert/Parameter/Should-HaveParameter.Tests.ps1
tst/functions/assert/Parameter/Should-NotHaveParameter.Tests.ps1

Add Should-HaveParameter and its Not variant.
Fix #2618

Add Should-HaveParameter

---

src/csharp/Pester/ContainerInfo.cs
src/functions/Output.ps1
tst/Pester.RSpec.Output.ts.ps1

Use a helper that formats the container name correctly for all container
types, notably also for ScriptBlocks.
fixes #2639

Fix container name display when running non-file types (fixes #2639).

---

src/functions/Output.ps1
tst/Pester.RSpec.InNewProcess.ts.ps1
tst/Pester.RSpec.Output.ts.ps1

Replace Result.Item with Result.Name to handle the ScriptBlock case. Previously, the container name was being reported only for files, not for ScriptBlocks (because files, unlike ScriptBlocks, have Result.Item).

Fix container name in ScriptBlock BeforeAll failures (fixes #2636).
