Functions/It.ps1

I still think there should be a test for this change, I just don't know exactly how to test pester from pester. :(

resolves #282

---

CHANGELOG.md
Functions/Describe.ps1

Describe fix

---

Functions/It.ps1

Add documentation of Pending and Skip parameters

---

Functions/Assertions/Should.ps1
Functions/It.Tests.ps1
Functions/It.ps1

Assertion fix

---

Functions/New-Fixture.ps1

Spelling change

---

README.md
en-US/about_Mocking.help.txt
en-US/about_Pester.help.txt

Code was already updated by PR #429.

Case insensitive replacement of Test in help  #428

---

Functions/Assertions/BeLike.Tests.ps1
Functions/Assertions/BeLike.ps1
Functions/Assertions/BeLikeExactly.Tests.ps1
Functions/Assertions/BeLikeExactly.ps1
en-US/about_should.help.txt

Created `Should BeLike` and `Should BeLikeExactly` assertions.

Fixes issue #454: Create Should BeLike assertion

---

Functions/SetupTeardown.ps1

Discarding output from Before/After Each/All

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Fixes #476 .  Also added some cleanup code to the 'Single quote in command/module name' describe in Mock.Tests.ps1 so it would stop producing errors if the tests are run more than once in the same PowerShell session.

Nested mock calls

---

en-US/about_TestDrive.help.txt

Live demo from IT Pro Con - fixing via github live on stage - Hi Dave!

Fixes minor typo in about_testdrive.help.txt

---

Functions/Assertions/Exist.Tests.ps1

The test is exactly same as previous one.

Remove duplicate test

---

en-US/about_Pester.help.txt

This PR replaces #513. I added an Examples section to about_Pester.help.txt.

Added Examples section

---

en-US/about_Pester.help.txt

Oops. Found a typo. Also removed extraneous tabs.

Fixed typo and tabs

---

Functions/Assertions/PesterThrow.Tests.ps1
Functions/Assertions/PesterThrow.ps1

Fix error messsage of Should Throw when null input is provided

---

Pester.psm1

Revised parameter help for Invoke-Pester -PassThru and -Quiet, including a new help example.

Revised help for PassThru and Quiet parameters

---

Pester.psm1

InconclusiveCount count was missing with -passthru

Added InconclusiveCount to Invoke-Pester output

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Using new PSv5 public interfaces for getting dynamic params of cmdlets

---

Pester.psm1

- added info about OutputFile, OutputFormat
- modified OutputXml
- lines shortened to about 80 chars
- tabs replaces with 4 spaces

Invoke-Pester - comment based help updated and reformatted

---

Functions/Describe.ps1

Help updated and reformatted for the function Describe - DevelopmentV4

---

Functions/Context.ps1

Help updated and reformatted for the function Context - DevelopmentV4

---

en-US/RSpec.psd1

Add commas to report summary in v4

---

Pester.psm1

Related issues: #492 , #648 
It's pull request for the Pester v. 3.4.* only.

[Pester 3.4.*] Help updated for the Invoke-Pester function

---

Functions/TestDrive.ps1

The related issue #648.
This commit replaces #668.

[Pester 3.4.*] Update help for the function Get-TestDriveItem

---

Functions/Assertions/Set-TestInconclusive.ps1

The related issue #648 
This pull is for Pester 3.4.6 too.

Help for the function Set-TestInconclusive added

---

Functions/TestDrive.ps1

[Pester v. 4.0.2] An example for Get-TestDriveItem added

---

Functions/Context.ps1

Help updated and reformatted for the function Context

---

Functions/Describe.ps1

A backport of https://github.com/pester/Pester/commit/e399446ad1476efef4a192cfd3996e73684ddcd7

Help of the function Describe updated and reformatted 

---

Functions/Context.ps1

A backport of https://github.com/pester/Pester/commit/adc25b509d668a873c2076608e2d9bd95982c402

Help of the function Context updated and reformatted

---

Functions/Assertions/BeNullOrEmpty.Tests.ps1
Functions/Assertions/BeNullOrEmpty.ps1

Fix BeNullOrEmpty to pass for an empty hashtable

---

Pester.Tests.ps1
Pester.psm1
chocolateyInstall.ps1

The backport of #691 
The fix of #689

Style rules corrected, trailing spaces removed, tabs replaces by spaces

---

Pester.Tests.ps1

Port of 1a864cc82895b8d8bc02ccbb5855e7ff4af24702

Rename indentation test

---

Functions/Gherkin.ps1

Remove unused variables

---

Functions/Assertions/Should.Tests.ps1
Functions/GherkinHook.Tests.ps1
Functions/GherkinHook.ps1
Functions/GherkinStep.Tests.ps1
Functions/Mock.Tests.ps1
Functions/New-Fixture.Tests.ps1
Functions/Output.ps1
Functions/TestResults.Tests.ps1
Functions/TestsRunningInCleanRunspace.Tests.ps1
Pester.Tests.ps1
Pester.psm1
build.psake.ps1

Violations reported by PSScriptAnalyzer v.1.11.0
The related issue #700 
Replace the pull request #707

Cleaning of code - PSScriptAnalyzer rules

---

Functions/Output.Tests.ps1
Functions/Output.ps1
en-US/RSpec.psd1

Added formatting function and tests, did only basic testing because the Write-Host cannot be mocked in Write-PesterStart and I don't want to dig too deep into the code.
Fix #699 
Fix #710

Fix header when passing in hashtables

---

Functions/Assertions/Be.Tests.ps1
Functions/Assertions/Be.ps1

Fix call depth overflow on non-collection types implementing IEnumerable

---

Functions/Output.Tests.ps1
Functions/Output.ps1

Add the improved error formatting back in, one of the tests is commented out becuase it behaves weirdly, because Should changed. 
Fix #815

Add error formatting back in

---

README.md

The related commit: 33b69150587b6ded1d6fcdcbe36b7079289e9fb7

Updating Pester on W10 and W2K16 - update - Fix #585

---

Functions/Gherkin.ps1

@KevinMarquette, I've added links to your blog post.
@Jaykul, I did this change to align organization of a comment based help to way as it's in other functions of  Pester.
The related issue: #808.

Invoke-Gherkin - reorganization and update of help

---

Functions/Context.ps1
Functions/Describe.ps1

Remove CommandUsed parameter from Describe

---

Functions/Gherkin.ps1
Functions/GherkinHook.ps1
Functions/GherkinStep.ps1

Update help of Gherkin-related functions

---

Pester.psd1
Pester.psm1

Throw on Assert-VerifiableMocks

---

.travis.yml

Add steps for Travis CI to run on both linux and osx

Update Travis CI to run on both linux and macOS

---

.github/ISSUE_TEMPLATE.md

To assist with Issue #636 I would like to propose the following template.

Created Github issue template

---

Examples/Gherkin/Gherkin-Scope.feature
Examples/Validator/Validator.Steps.ps1
Functions/Gherkin.Tests.ps1
Functions/Gherkin.ps1
Functions/GherkinHook.Tests.ps1
Functions/GherkinHook.ps1
Functions/GherkinStep.Tests.ps1

Fix the linux case-sensitive problem causing #937

Fix Gherkin for Linux (#937) and PS2

---

.travis.yml
Pester.Tests.ps1
Pester.psd1

Use pre-release for PSGallery

---

Functions/Assertions/Set-TestInconclusive.ps1
Functions/It.ps1

Backport of 
- PR #723
- PR #778

[V3Maintenance] Add help for set test inconclusive

---

.travis.yml
Pester.Tests.ps1

The related issues
- #648 
- #720
- #808
Replaces the pull request #955.

Add tests to verify completeness of a comment based help

---

Functions/Assertions/PesterThrow.Tests.ps1
Functions/Assertions/PesterThrow.ps1

Adds exception message to out put of Should -not -throw

#1009 fix general error

---

Functions/TestResults.Tests.ps1
Functions/TestResults.ps1

Support saving result files to the path provided as a PSDrive

---

Functions/Mock.Tests.ps1

remove dynamic module after mock tests

---

Examples/Planets/Get-Planet.Tests.ps1
Examples/Planets/Get-Planet.ps1
Functions/Describe.Tests.ps1
Functions/Describe.ps1
Functions/Mock.ps1
Pester.Tests.ps1
Pester.psm1

Use wildcards for tags

---

Functions/Mock.Tests.ps1

An additional tests based on @mikeclayton's [proposal](https://github.com/pester/Pester/issues/949#issue-275864940).
Fix #949

The test for nonexisting module behavior check

---

Functions/Gherkin.ps1
Pester.psm1

Remove splitting tags on whitespace

---

README.md

This is just modifying readme.md, as per #1050.
See it [in action example](https://ci.appveyor.com/project/nohwnd/planets) is already updated according to this.

Document integration with AppVeyor Ubuntu build

---

Functions/Describe.ps1

exclude non-tagged describes from tagged run

---

Examples/Validator/Validator.feature
Functions/Gherkin.Tests.ps1
Functions/Gherkin.ps1
Functions/GherkinHook.Tests.ps1

Adds support for 'Scenario Template', which can be used in place of
'Scenario Outline'. Fixes #1123.

Adds support for 'Scenario Template'

---

Functions/TestDrive.Tests.ps1
Functions/TestDrive.ps1

see https://github.com/pester/Pester/issues/1100

Added fix for deleting symlinks in TestDrive

---

Functions/Mock.ps1

To support asserting mocks with Assert-MockCalled for Gherkin-style
tests, allow the Scope parameter to also accept the "keywords" Feature
and Scenario.
Prior to this fix, using the Scope parameter with anything but a numeric
scope was not possible. Now you can specify that the scope associated
with the Gherkin Feature or Scenario should be used when asserting a
mock.
Fixes #1164.

Assert-MockCalled -Scope: allow Feature and Scenario

---

Functions/Set-ItResult.ps1

Several fixes for `Set-ItResult` function help.

Fix Set-ItResult function help.

---

README.md

Clarify meaning

---

.appveyor.yml

Add 'WMF 4' image to AppVeyor build matrix

---

Examples/Gherkin/JustForReporting.Steps.ps1
Examples/Gherkin/JustForReporting1.feature
Examples/Gherkin/JustForReporting2.feature
Functions/Gherkin.Tests.ps1
Functions/Gherkin.ps1

Improve NUnit xml report

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

The pull request slightly updates GitHub templates.

Minor correction of GitHub templates

---

Functions/Environment.Tests.ps1
Functions/Environment.ps1
Functions/TestRegistry.ps1

Fixes more TestRegistry parallel issues

---

Functions/Mock.ps1
Functions/OuterMock.Tests.ps1

WIP: Check if function exists before removing it

---

Functions/InModuleScope.ps1
Functions/Mock.ps1
Functions/Output.ps1
Functions/Pester.Debugging.ps1
Functions/Pester.Scoping.ps1
Functions/Pester.SessionState.Mock.ps1
Functions/TestResults.ps1
Pester.psm1
README.md
new-runtimepoc/Pester.Runtime.psm1
new-runtimepoc/Pester.Runtime.ts.ps1
new-runtimepoc/Pester.Utility.psm1
new-runtimepoc/ReloadAndInvokePester.ps1

Fix the timing and improve performance
Fixes #1269

Fix timing

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Add parameters to mock to relax commands

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1
new-runtimepoc/ReloadAndInvokePester.ps1

When using `-ModuleName` run mocks and mock filters in the same scope which is the test scope.

Run mocks in test scope

---

Functions/Assertions/Be.Tests.ps1
Functions/Assertions/PesterThrow.Tests.ps1
Functions/Assertions/PesterThrow.ps1
Functions/Mock.Tests.ps1
Functions/PesterState.ps1
new-runtimepoc/ReloadAndInvokePester.ps1

Compare messages and errorIds with -like wildcards

---

Functions/Mock.ps1
Functions/SetupTeardown.ps1
Pester.psd1
Pester.psm1
demo/Get-Pokemon.Good.Tests.ps1
new-runtimepoc/Pester.Mock.RSpec.ts.ps1
new-runtimepoc/Pester.RSpec.ts.ps1
new-runtimepoc/Pester.Runtime.psm1
new-runtimepoc/Pester.Runtime.ts.ps1
new-runtimepoc/ReloadAndInvokePester.ps1

Use BeforeAll instead of Add-Dependency 
Rename Add-FreeFloatingCode to Anywhere
Remove ISE snippets
Fixes #1283

Use BeforeAll instead of Add-Dependency

---

new-runtimepoc/Pester.Runtime.psm1

Write error when running non-interactively

---

Functions/Mock.Tests.ps1
Functions/Mock.ps1

Cmdlet dynamic param

---

Functions/Output.ps1
en-US/Gherkin.psd1
en-US/RSpec.psd1

Fix issue #1342.
Told you I think ASCII art and most things retro are 😎 .

Add header to Pester output that shows the version

---

Functions/TestResults.Tests.ps1
Functions/TestResults.ps1
Pester.psm1
buildPSGalleryPackage.ps1
junit_schema_4.xsd

Fixes #1346 
This PR will be in draft so progress on the JUnitXml implementation can be tracked / discussed. Once done, it will be promoted to a generic PR

Add JUnitXml to OutputFormat

---

Functions/Assertions/Set-TestInconclusive.ps1
Functions/Context.ps1
Functions/Describe.ps1
Functions/Gherkin.ps1
Functions/GherkinStep.ps1
Functions/InModuleScope.ps1
Functions/It.ps1
Functions/Mock.ps1
Functions/New-Fixture.ps1
Functions/New-MockObject.ps1
Functions/Set-ItResult.ps1
Pester.psm1

As discussed in https://github.com/pester/docs/issues/9

Adds code fencing to the multi-line Get-Help code examples

---

.travis.yml
Dependencies/Axiom/Verify-Equal.ps1
Functions/Context.ps1
Functions/Describe.ps1
Functions/It.ps1
Functions/Mock.ps1
Functions/Output.ps1
Functions/TestResults.ps1
en-US/RSpec.psd1
new-runtimepoc/Pester.RSpec.Nunit.TestResults.ts.ps1
new-runtimepoc/Pester.RSpec.ResultObject.ts.ps1
new-runtimepoc/Pester.RSpec.ps1
new-runtimepoc/Pester.RSpec.ts.ps1
new-runtimepoc/Pester.Runtime.psm1
new-runtimepoc/Pester.Runtime.ts.ps1

Implement `-Skip` on `It`, `Describe` and `Context`. 
Fix #1266

Implement skip and not run

---

README.md

Update link to Pester limitations

---

Functions/Output.ps1
Pester.psm1
demo/focus/Focus.Tests.ps1
new-runtimepoc/Configuration.cs
new-runtimepoc/ConversionTests.cs
new-runtimepoc/Pester.RSpec.Configuration.ts.ps1
new-runtimepoc/Pester.RSpec.ps1
new-runtimepoc/Pester.RSpec.ts.ps1
new-runtimepoc/Pester.Rspec.Filtering.ts.ps1
new-runtimepoc/Pester.Runtime.psm1
new-runtimepoc/Pester.Runtime.ts.ps1
new-runtimepoc/Pester.csproj
new-runtimepoc/p.psm1

Improve filtering

---

.appveyor.yml
.travis.yml
Pester.psm1
azure-pipelines.yml
new-runtimepoc/Configuration.cs
new-runtimepoc/Pester.Mock.RSpec.ts.ps1
new-runtimepoc/Pester.RSpec.Configuration.ts.ps1
new-runtimepoc/Pester.RSpec.Nunit.TestResults.ts.ps1
new-runtimepoc/Pester.RSpec.ResultObject.ts.ps1
new-runtimepoc/Pester.RSpec.ts.ps1
new-runtimepoc/Pester.Rspec.Filtering.ts.ps1
new-runtimepoc/Pester.Runtime.psm1
test.ps1

Remove -ScriptBlock from the simple interface

Remove scriptblock from simple api

---

Functions/Context.ps1
Functions/Describe.ps1
Functions/It.ps1
Functions/Output.ps1

Focused and fail output on null verbosity

---

Functions/Output.Tests.ps1
Functions/TestResults.ps1
Pester.psm1
new-runtimepoc/Configuration.cs
new-runtimepoc/Pester.Mock.RSpec.ts.ps1
new-runtimepoc/Pester.RSpec.Configuration.ts.ps1
new-runtimepoc/Pester.RSpec.Demo.ts.ps1
new-runtimepoc/Pester.RSpec.Nunit.TestResults.ts.ps1
new-runtimepoc/Pester.RSpec.ResultObject.ts.ps1
new-runtimepoc/Pester.RSpec.ps1
new-runtimepoc/Pester.RSpec.ts.ps1
new-runtimepoc/Pester.Runtime.ts.ps1
test.ps1

Clean result object

---

.appveyor.yml
Pester.psd1
Pester.psm1
new-runtimepoc/Configuration.cs
new-runtimepoc/Pester.RSpec.LegacyResultObject.ts.ps1
new-runtimepoc/Pester.RSpec.Pester4ResultObject.ts.ps1
new-runtimepoc/Pester.Types.ps1

Add ConvertTo-Pester4Result

---

.appveyor.yml
.travis.yml
Pester.psm1
azure-pipelines.yml
new-runtimepoc/Configuration.cs
new-runtimepoc/Pester.Mock.RSpec.ts.ps1
new-runtimepoc/Pester.RSpec.Configuration.ts.ps1
new-runtimepoc/Pester.RSpec.Demo.ts.ps1
new-runtimepoc/Pester.RSpec.Nunit.TestResults.ts.ps1
new-runtimepoc/Pester.RSpec.ResultObject.ts.ps1
new-runtimepoc/Pester.RSpec.ts.ps1
new-runtimepoc/Pester.Rspec.Filtering.ts.ps1
new-runtimepoc/Pester.Runtime.ts.ps1

Add -PassThru

---

Pester.psm1
new-runtimepoc/Configuration.cs
new-runtimepoc/Pester.RSpec.Configuration.ts.ps1
new-runtimepoc/Pester.Rspec.Filtering.ts.ps1
new-runtimepoc/Pester.Runtime.psm1
new-runtimepoc/Pester.Runtime.ts.ps1
new-runtimepoc/Pester.Utility.ps1

Add filter to filter on full name of a test describe1.describe2.test1 by like wildcards
Fixes #1483

Add -FullName filter

---

README.md

This will be helpful for people running tests on Ubuntu

v5 Docs: Fix casing of default rest results file

---

src/Pester.ps1

Fix configuration reference so we don't leak configs among runs.

Fix config ref

---

src/functions/Mock.ps1
tst/Pester.Mock.RSpec.ts.ps1
tst/functions/Mock.Tests.ps1

Fix splatting default params in Mock
Fixes #1519

[WIP] Splatting in mock

---

src/functions/Coverage.ps1

Fix path in code coverage

---

src/functions/Output.ps1

Fixing https://twitter.com/JustinWGrote/status/1261086888326135808?s=20

Separate file output with just single space

---

src/functions/assertions/HaveParameter.ps1
tst/functions/assertions/HaveParameter.Tests.ps1

Add alias parameter to -HaveParameter

---

README.md
src/functions/Pester.SessionState.Mock.ps1
tst/Pester.Mock.RSpec.ts.ps1
tst/Pester.RSpec.Configuration.ts.ps1
tst/Pester.RSpec.Demo.ts.ps1
tst/Pester.RSpec.Junit.TestResults.ts.ps1
tst/Pester.RSpec.Nunit.TestResults.ts.ps1
tst/Pester.RSpec.Pester4ResultObject.ts.ps1
tst/Pester.RSpec.ts.ps1
tst/Pester.Rspec.Filtering.ts.ps1

Allow mocks in top-level BeforeAll

---

README.md
src/Pester.ps1
src/csharp/Pester/Configuration.cs
src/functions/Output.ps1
test.ps1
tst/Pester.RSpec.Configuration.ts.ps1
tst/Pester.RSpec.Demo.ts.ps1
tst/functions/Pester.TestDrive.ts.ps1
tst/functions/Pester.TestRegistry.ts.ps1

Minimal is the new Normal, and Normal is Detailed

---

src/csharp/Pester/Configuration.cs

Fix casting from join path

---

build.ps1

Remove duplicates before building

---

README.md
src/Pester.psd1

Release 5.0.0

---

src/functions/assertions/Should.ps1

Returning from Invoke-Assertion when $entry is null.

Allowing for @ to be the first non-whitespace character after Should.

---

src/Pester.ps1
src/functions/Pester.SessionState.Mock.ps1
src/functions/assertions/Be.ps1
src/functions/assertions/BeGreaterThan.ps1
src/functions/assertions/BeIn.ps1
src/functions/assertions/BeLessThan.ps1
src/functions/assertions/BeLike.ps1
src/functions/assertions/BeLikeExactly.ps1
src/functions/assertions/BeNullOrEmpty.ps1
src/functions/assertions/BeOfType.ps1
src/functions/assertions/BeTrueOrFalse.ps1
src/functions/assertions/Contain.ps1
src/functions/assertions/Exist.ps1
src/functions/assertions/FileContentMatch.ps1
src/functions/assertions/FileContentMatchExactly.ps1
src/functions/assertions/FileContentMatchMultiline.ps1
src/functions/assertions/HaveCount.ps1
src/functions/assertions/HaveParameter.ps1
src/functions/assertions/Match.ps1
src/functions/assertions/MatchExactly.ps1
src/functions/assertions/PesterThrow.ps1

Refer to Add-ShouldOperator safely

---

src/Pester.RSpec.ps1
src/functions/Environment.ps1
src/functions/TestDrive.ps1
src/functions/TestRegistry.ps1
src/functions/assertions/Should.ps1
tst/Pester.Mock.RSpec.ts.ps1

Fix test path

---

README.md

Added Import-Module Pester in the instructions... basic but I had to google for it :)

Added Import-Module Pester in the instructions - Update README.md

---

src/Pester.ps1
src/Pester.psd1
src/Pester.psm1
tst/Pester.RSpec.ts.ps1

Add BeforeDiscovery block to allow grouping code that needs to run before discovery.

Add BeforeDiscovery semantic block

---

src/Pester.Runtime.psm1
src/csharp/Pester/Container.cs
tst/Pester.RSpec.ts.ps1

Allow AfterAll in top-level

---

src/functions/Context.ps1
src/functions/Describe.ps1
src/functions/Output.ps1
tst/Pester.RSpec.Output.ts.ps1

Write all parent blocks to screen on first test or on failed block

---

src/Pester.Runtime.psm1
tst/Pester.RSpec.Nunit.TestResults.ts.ps1

Default to expanded name and path

---

src/functions/Mock.ps1
tst/Pester.Mock.RSpec.ts.ps1

Clean up mocks in the session state where we defined them

---

src/Pester.ps1

Always set exit code exit

---

CONTRIBUTING.md
build.ps1
test.ps1

- Renames BUILD.md to CONTRIBUTING.md to be more discoverable for contributors.
- Updated text around how to build the module.
Fixes #1692
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pester/pester/1697)

Add CONTRIBUTING.md (renames BUILD.md)

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add labels to templates

---

src/functions/TestResults.ps1
tst/Pester.RSpec.Junit.TestResults.ts.ps1

Fix counts of skipped and notrun
Fix #1757

Fix JUnit counts for skipped and notrun

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/commandhelp_issue.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Updated github templates to be more compact by removing unnecessary linebreaks.
Fix #1767

Compact github templates

---

src/functions/Pester.SessionState.Mock.ps1
tst/Pester.Mock.RSpec.ts.ps1

Fix searching for mock table when deep in tests

---

src/functions/assertions/Be.ps1
test.ps1
tst/Pester.Mock.RSpec.ts.ps1
tst/Pester.RSpec.Junit.TestResults.ts.ps1
tst/Pester.RSpec.Nunit.TestResults.ts.ps1
tst/functions/Output.Tests.ps1
tst/functions/assertions/Be.Tests.ps1

Useful string assert message

---

src/functions/Mock.ps1

In mock parameter filter show variables that are overwritten by parameter variables. 
Also show result of the mock filter and it's truthiness / falsiness. 
Fix #1873

Improve logging for mock parameter filter

---

src/en-US/about_TestDrive.help.txt

Fix testdrive example

---

build.ps1
src/Pester.Runtime.ps1
src/Script.ps1
tst/Pester.RSpec.ts.ps1
tst/Pester.Runtime.ts.ps1

Isolating the scripts to different script: scope on discovery for scriptblocks (files are naturally isolated) and on run.

Isolate scripts and scriptblocks on run

---

src/Main.ps1

Set exit code always. On success, on throw, and on exit.

Set exit code

---

src/functions/Mock.ps1
tst/Pester.Mock.ClassMetadata.ps1
tst/Pester.Mock.RSpec.ts.ps1

Resolve metadata in the correct scope

---

src/csharp/Pester/DictionaryExtensions.cs
src/csharp/Pester/StringArrayOption.cs
tst/Pester.RSpec.Configuration.ts.ps1

Fix psobject to string array

---

build.ps1
src/Main.ps1
src/Pester.RSpec.ps1

Generate config section from the object. 
Fix #1922

Generate config docs

---

build.ps1

Fix default values in docs when they are array.

Fix generation for array default values

---

src/Main.ps1

Fixes #1902
Related pester/docs#97

Update config-replacements for legacy options

---

src/Pester.Runtime.ps1
src/functions/Output.ps1

Hide test run was skipped message when output is None

---

src/Main.ps1
src/functions/Describe.ps1
src/functions/SetupTeardown.ps1
src/functions/assertions/Should.ps1

Remove about links they break website MDX

---

azure-pipelines.yml
build.ps1
src/Pester.RSpec.ps1

Move the build from the self-hosted agent to azure hosted and build on 5.1 there.
Fix the BOM in generated file on PS7.

Build on PS5.1

---

src/functions/Coverage.ps1
tst/functions/Coverage.Tests.ps1

Fix failure on zero analyzed commands

---

azure-pipelines.yml

Removing VMs that are no longer hosted by Microsoft and using more recent Operating Systems.

Use newer images in our pipeline

---

src/functions/New-Fixture.ps1

Closes #2096
Fixing comment-based help for New-Fixture cmdlet:
- updated examples' code (incorrect sequence of positional parameters)
- updated info about the content of files generated by this cmdlet

Update help for New-Fixture

---

azure-pipelines.yml
src/Main.ps1
src/Pester.RSpec.ps1
src/Pester.Utility.ps1
src/Pester.psd1
src/csharp/Pester/CodeCoverageConfiguration.cs
src/csharp/Pester/DictionaryExtensions.cs
src/csharp/Pester/FilterConfiguration.cs
src/functions/Coverage.ps1
src/functions/Describe.ps1
src/functions/InModuleScope.ps1
src/functions/New-MockObject.ps1
src/functions/Set-ItResult.ps1
src/functions/SetupTeardown.ps1
tst/CoverageTestFile.ps1
tst/PesterConfiguration.Tests.ps1
tst/functions/New-MockObject.Tests.ps1

Merge changes from release branch back to main.

Forward merge rel/5.3.x

---

build.ps1

Minor improvements to builds script
- Adds `-Import` option to build
- Adds missing quotes to paths using `$PSScriptRoot`
- Only reads content of source files during inline-build
- `-Load` now uses manifest to include format files

Minor improvements to build script

---

publish/signModule.ps1

Sign format files

---

src/functions/TestDrive.ps1
src/functions/TestRegistry.ps1

Code cleanup. Move PSDrive-cleanup into `Start`-pluginstep.

Use Start plugin-step for TestDrive and TestRegistry PSDrive cleanup

---

src/functions/Context.ps1
src/functions/Describe.ps1

Fixes two small typos.
Replaces https://github.com/pester/docs/pull/257.

Fix docs typos

---

src/functions/New-MockObject.ps1

Minor cleanup and add missing code fence to improve readability.
Related https://github.com/pester/docs/pull/256#pullrequestreview-1347425303

Update New-MockObject help

---

Pester.BuildAnalyzerRules/Pester.BuildAnalyzerRules.psm1

Fix typos in Measure-ObjectCmdlets rule

Fix typos in Pester.BuildAnalyzerRules

---

src/functions/Environment.ps1
src/functions/Get-ShouldOperator.ps1
src/functions/Pester.Debugging.ps1

To avoid polluting $Error with errors we handle and ignore internally

Replace ErrorAction SilentlyContinue with Ignore

---

docs/Examples/Planets/Get-Planet.Tests.ps1
src/Module.ps1
src/Pester.Runtime.ps1
src/csharp/Pester/Tracing/Tracer.cs
src/functions/Coverage.ps1
src/functions/Describe.ps1
src/functions/Mock.ps1
src/functions/Output.ps1
src/functions/Pester.Debugging.ps1
src/functions/Pester.SessionState.Mock.ps1
src/functions/assertions/Be.ps1
src/functions/assertions/Should.ps1
tst/CoverageTestFile.ps1
tst/Pester.RSpec.InNewProcess.ts.ps1
tst/Pester.RSpec.Output.ts.ps1
tst/Pester.RSpec.ts.ps1
tst/Pester.Runtime.ts.ps1
tst/p.psm1

Correct typos in PowerShell and C# comments.

Correct typos in comments

---

src/csharp/Pester/BoolOption.cs
src/csharp/Pester/CodeCoverageConfiguration.cs
src/csharp/Pester/ConfigurationSection.cs
src/csharp/Pester/ContainerInfoArrayOption.cs
src/csharp/Pester/Coverage.cs
src/csharp/Pester/DecimalOption.cs
src/csharp/Pester/DictionaryExtensions.cs
src/csharp/Pester/Factory.cs
src/csharp/Pester/IntOption.cs
src/csharp/Pester/PesterConfigurationDeserializer.cs
src/csharp/Pester/RunConfiguration.cs
src/csharp/Pester/ScriptBlockArrayOption.cs
src/csharp/Pester/ShouldConfiguration.cs
src/csharp/Pester/StringArrayOption.cs
src/csharp/Pester/StringOption.cs
src/csharp/Pester/Test.cs
src/csharp/Pester/TestDriveConfiguration.cs
src/csharp/Pester/TestRegistryConfiguration.cs
src/csharp/Pester/ToStringConverter.cs
src/csharp/Pester/Tracing/CodeCoverageTracer.cs
src/csharp/Pester/Tracing/ExternalTracerAdapter.cs
src/csharp/Pester/Tracing/Tracer.cs
src/csharp/Pester/Tracing/TracerHostUI.cs

Now that language version is increased to latest, we can simplify some of our C# code using newer features.
This fixes most findings reported by Roslyn analyzer.

Address analyzer suggestions for csharp-project

---

src/functions/TestResults.ps1

fixed typo in propertyy params in TestReults.ps1

---

README.md

Add the new thumbprint used for signing via HSM.

Update certificate thumbprint

---

publish/filesToPublish.ps1
publish/release.ps1

Extract files so we can keep the script for publish the same on rel/5.x and main.

Extract files to publish from release script

---

tst/functions/Add-ShouldOperator.ts.ps1

Add tests for typical custom assertions to make sure we don't break specifications from docs.
Fix #2384

Add tests for custom assertions

---

build.ps1
global.json
publish/filesToPublish.ps1
src/Pester.Types.ps1
src/csharp/Pester/Pester.csproj
src/csharp/Pester/packages.lock.json
src/csharp/PesterTests/PesterTests.csproj
src/csharp/PesterTests/packages.lock.json

Update to latest deps, and supported tfm

Update to net8 and newer dep

---

src/functions/Output.ps1

Remove dead code in Output.ps1

---

src/functions/assert/Time/Should-BeFasterThan.ps1
tst/functions/assert/Time/Should-BeFasterThan.Tests.ps1

Add -Because to Should-BeFasterThan

---

.github/workflows/code-analysis.yml
PSScriptAnalyzerSettings.psd1

Bumps psmodulecache action to latest to fix broken actions/cache dependency

Fix Code analysis workflow
